// === Helper: generate calif bindings for vigente plan ===
const YEAR_NAMES = ['Primer AÃ±o', 'Segundo AÃ±o', 'Tercer AÃ±o', 'Cuarto AÃ±o', 'Quinto AÃ±o']
const MATERIAS_VIGENTE: Record<number, string[]> = {
  1: ['Castellano', 'InglÃ©s', 'MatemÃ¡ticas', 'EducaciÃ³n FÃ­sica', 'Arte y Patrimonio', 'Ciencias Naturales', 'GeografÃ­a, Historia y CiudadanÃ­a'],
  2: ['Castellano', 'InglÃ©s', 'MatemÃ¡ticas', 'EducaciÃ³n FÃ­sica', 'Arte y Patrimonio', 'Ciencias Naturales', 'GeografÃ­a, Historia y CiudadanÃ­a'],
  3: ['Castellano', 'InglÃ©s', 'MatemÃ¡ticas', 'EducaciÃ³n FÃ­sica', 'FÃ­sica', 'QuÃ­mica', 'BiologÃ­a', 'GeografÃ­a, Historia y CiudadanÃ­a', 'FormaciÃ³n SoberanÃ­a Nacional'],
  4: ['Castellano', 'InglÃ©s', 'MatemÃ¡ticas', 'EducaciÃ³n FÃ­sica', 'FÃ­sica', 'QuÃ­mica', 'BiologÃ­a', 'GeografÃ­a, Historia y CiudadanÃ­a', 'FormaciÃ³n SoberanÃ­a Nacional'],
  5: ['Castellano', 'InglÃ©s', 'MatemÃ¡ticas', 'EducaciÃ³n FÃ­sica', 'FÃ­sica', 'QuÃ­mica', 'BiologÃ­a', 'Ciencias de la Tierra', 'GeografÃ­a, Historia y CiudadanÃ­a', 'FormaciÃ³n SoberanÃ­a Nacional'],
}

function generateCalifBindings() {
  const groups: { group: string; bindings: { value: string; label: string }[] }[] = []
  for (let y = 1; y <= 5; y++) {
    const materias = MATERIAS_VIGENTE[y] || []
    const bindings: { value: string; label: string }[] = []
    for (let s = 0; s < materias.length; s++) {
      const nombre = materias[s]
      bindings.push(
        { value: `calif.${y}.${s}.materia`, label: `${s + 1}. ${nombre}` },
        { value: `calif.${y}.${s}.nota`, label: `${s + 1}. ${nombre} â€” Nota` },
        { value: `calif.${y}.${s}.literal`, label: `${s + 1}. ${nombre} â€” Literal` },
        { value: `calif.${y}.${s}.te`, label: `${s + 1}. ${nombre} â€” T-E` },
        { value: `calif.${y}.${s}.mes`, label: `${s + 1}. ${nombre} â€” Mes` },
        { value: `calif.${y}.${s}.anio`, label: `${s + 1}. ${nombre} â€” AÃ±o` },
        { value: `calif.${y}.${s}.inst`, label: `${s + 1}. ${nombre} â€” Inst. Educ.` },
        { value: `calif.${y}.${s}.numero`, label: `${s + 1}. ${nombre} â€” NÂ°` },
      )
    }
    groups.push({ group: `Calificaciones â€” ${YEAR_NAMES[y - 1]}`, bindings })
  }
  return groups
}

export const DATA_BINDINGS_VIGENTE: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Estudiante', bindings: [
    { value: 'student.cedula', label: 'CÃ©dula de Identidad' },
    { value: 'student.apellidos', label: 'Apellidos' },
    { value: 'student.nombres', label: 'Nombres' },
    { value: 'student.fechaNacimiento', label: 'Fecha de Nacimiento' },
    { value: 'student.pais', label: 'PaÃ­s de Nacimiento' },
    { value: 'student.estado', label: 'Estado de Nacimiento' },
    { value: 'student.municipio', label: 'Municipio de Nacimiento' },
    { value: 'student.lugarFechaNac', label: 'Lugar y Fecha de Nacimiento' },
  ]},
  { group: 'InstituciÃ³n (Escuela)', bindings: [
    { value: 'school.codigo', label: 'CÃ³digo OD' },
    { value: 'school.denominacion', label: 'DenominaciÃ³n' },
    { value: 'school.direccion', label: 'DirecciÃ³n' },
    { value: 'school.telefono', label: 'TelÃ©fono' },
    { value: 'school.municipio', label: 'Municipio' },
    { value: 'school.estado', label: 'Estado' },
    { value: 'school.cdcce', label: 'CDCEE' },
  ]},
  { group: 'Documento', bindings: [
    { value: 'doc.planEstudio', label: 'Plan de Estudio' },
    { value: 'doc.codigo', label: 'CÃ³digo Plan' },
    { value: 'doc.lugar', label: 'Lugar' },
    { value: 'doc.fechaExpedicion', label: 'Fecha de ExpediciÃ³n' },
    { value: 'doc.observaciones', label: 'Observaciones' },
    { value: 'doc.promedioAcumulado', label: 'Promedio Acumulado' },
    { value: 'doc.acta', label: 'Acta' },
    { value: 'doc.actaFecha', label: 'Acta â€” Fecha' },
    { value: 'doc.actaAnio', label: 'Acta â€” AÃ±o' },
  ]},
  { group: 'Observaciones CertificaciÃ³n', bindings: [
    { value: 'obsCert.0', label: 'OBS.CERT â€” LÃ­nea 1' },
    { value: 'obsCert.1', label: 'OBS.CERT â€” LÃ­nea 2' },
    { value: 'obsCert.2', label: 'OBS.CERT â€” LÃ­nea 3' },
    { value: 'obsCert.3', label: 'OBS.CERT â€” LÃ­nea 4' },
    { value: 'rawData.OBS.NOTAS.L1', label: 'Obs. Notas â€” Linea 1' },
    { value: 'rawData.OBS.NOTAS.L2', label: 'Obs. Notas â€” Linea 2' },
    { value: 'rawData.OBS.NOTAS.L3', label: 'Obs. Notas â€” Linea 3' },
  ]},
  { group: 'Literales Finales', bindings: [
    { value: 'doc.literalFinal.0', label: 'Literal Final â€” 1er AÃ±o' },
    { value: 'doc.literalFinal.1', label: 'Literal Final â€” 2do AÃ±o' },
    { value: 'doc.literalFinal.2', label: 'Literal Final â€” 3er AÃ±o' },
    { value: 'doc.literalFinal.3', label: 'Literal Final â€” 4to AÃ±o' },
    { value: 'doc.literalFinal.4', label: 'Literal Final â€” 5to AÃ±o' },
  ]},
  { group: 'Director', bindings: [
    { value: 'director.nombre', label: 'Nombre del Director (Z6)' },
    { value: 'director.cedula', label: 'CÃ©dula del Director (Z7)' },
    { value: 'expedicion.fecha', label: 'Fecha de ExpediciÃ³n (Z4 / hoy)' },
    { value: 'expedicion.lugar', label: 'Lugar de ExpediciÃ³n (AH4 / MIRANDA)' },
  ]},
  { group: 'Director CDCEE', bindings: [
    { value: 'cdcee.nombre', label: 'Nombre Director CDCEE' },
    { value: 'cdcee.cedula', label: 'CÃ©dula Director CDCEE' },
  ]},
  { group: 'Instituciones Educativas', bindings: [
    { value: 'inst.0.denominacion', label: 'InstituciÃ³n 1 â€” DenominaciÃ³n' },
    { value: 'inst.0.localidad', label: 'InstituciÃ³n 1 â€” Localidad' },
    { value: 'inst.0.ef', label: 'InstituciÃ³n 1 â€” E.F.' },
    { value: 'inst.1.denominacion', label: 'InstituciÃ³n 2 â€” DenominaciÃ³n' },
    { value: 'inst.1.localidad', label: 'InstituciÃ³n 2 â€” Localidad' },
    { value: 'inst.1.ef', label: 'InstituciÃ³n 2 â€” E.F.' },
    { value: 'inst.2.denominacion', label: 'InstituciÃ³n 3 â€” DenominaciÃ³n' },
    { value: 'inst.2.localidad', label: 'InstituciÃ³n 3 â€” Localidad' },
    { value: 'inst.2.ef', label: 'InstituciÃ³n 3 â€” E.F.' },
    { value: 'inst.3.denominacion', label: 'InstituciÃ³n 4 â€” DenominaciÃ³n' },
    { value: 'inst.3.localidad', label: 'InstituciÃ³n 4 â€” Localidad' },
    { value: 'inst.3.ef', label: 'InstituciÃ³n 4 â€” E.F.' },
    { value: 'inst.4.denominacion', label: 'InstituciÃ³n 5 â€” DenominaciÃ³n' },
    { value: 'inst.4.localidad', label: 'InstituciÃ³n 5 â€” Localidad' },
    { value: 'inst.4.ef', label: 'InstituciÃ³n 5 â€” E.F.' },
  ]},
  ...generateCalifBindings(),
  { group: 'OrientaciÃ³n y Convivencia', bindings: [
    { value: 'orient.0.anio', label: '1er AÃ±o â€” AÃ±o Escolar' },
    { value: 'orient.0.literal', label: '1er AÃ±o â€” Literal' },
    { value: 'orient.1.anio', label: '2do AÃ±o â€” AÃ±o Escolar' },
    { value: 'orient.1.literal', label: '2do AÃ±o â€” Literal' },
    { value: 'orient.2.anio', label: '3er AÃ±o â€” AÃ±o Escolar' },
    { value: 'orient.2.literal', label: '3er AÃ±o â€” Literal' },
    { value: 'orient.3.anio', label: '4to AÃ±o â€” AÃ±o Escolar' },
    { value: 'orient.3.literal', label: '4to AÃ±o â€” Literal' },
    { value: 'orient.4.anio', label: '5to AÃ±o â€” AÃ±o Escolar' },
    { value: 'orient.4.literal', label: '5to AÃ±o â€” Literal' },
  ]},
  { group: 'Grupos (CreaciÃ³n/RecreaciÃ³n)', bindings: [
    { value: 'grupo.0.anio', label: '1er AÃ±o â€” AÃ±o Escolar' },
    { value: 'grupo.0.grupo', label: '1er AÃ±o â€” Nombre Grupo' },
    { value: 'grupo.0.literal', label: '1er AÃ±o â€” Literal' },
    { value: 'grupo.1.anio', label: '2do AÃ±o â€” AÃ±o Escolar' },
    { value: 'grupo.1.grupo', label: '2do AÃ±o â€” Nombre Grupo' },
    { value: 'grupo.1.literal', label: '2do AÃ±o â€” Literal' },
    { value: 'grupo.2.anio', label: '3er AÃ±o â€” AÃ±o Escolar' },
    { value: 'grupo.2.grupo', label: '3er AÃ±o â€” Nombre Grupo' },
    { value: 'grupo.2.literal', label: '3er AÃ±o â€” Literal' },
    { value: 'grupo.3.anio', label: '4to AÃ±o â€” AÃ±o Escolar' },
    { value: 'grupo.3.grupo', label: '4to AÃ±o â€” Nombre Grupo' },
    { value: 'grupo.3.literal', label: '4to AÃ±o â€” Literal' },
    { value: 'grupo.4.anio', label: '5to AÃ±o â€” AÃ±o Escolar' },
    { value: 'grupo.4.grupo', label: '5to AÃ±o â€” Nombre Grupo' },
    { value: 'grupo.4.literal', label: '5to AÃ±o â€” Literal' },
  ]},
  { group: 'Plantel por Materia (Constancia)', bindings: [
    { value: 'rawData.INST_NAME.CA.1', label: 'Nombre Plantel - Castellano (1)' },
    { value: 'rawData.INST_LOCAL.CA.1', label: 'Localidad Plantel - Castellano (1)' },
    { value: 'rawData.INST_EF.CA.1', label: 'E.F. Plantel - Castellano (1)' },
    { value: 'rawData.INST_NAME.IN.1', label: 'Nombre Plantel - Ingles (1)' },
    { value: 'rawData.INST_LOCAL.IN.1', label: 'Localidad Plantel - Ingles (1)' },
    { value: 'rawData.INST_EF.IN.1', label: 'E.F. Plantel - Ingles (1)' },
    { value: 'rawData.INST_NAME.MA.1', label: 'Nombre Plantel - Matematica (1)' },
    { value: 'rawData.INST_LOCAL.MA.1', label: 'Localidad Plantel - Matematica (1)' },
    { value: 'rawData.INST_EF.MA.1', label: 'E.F. Plantel - Matematica (1)' },
    { value: 'rawData.INST_NAME.EF.1', label: 'Nombre Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_LOCAL.EF.1', label: 'Localidad Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_EF.EF.1', label: 'E.F. Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_NAME.AP.1', label: 'Nombre Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_LOCAL.AP.1', label: 'Localidad Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_EF.AP.1', label: 'E.F. Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_NAME.CN.1', label: 'Nombre Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_LOCAL.CN.1', label: 'Localidad Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_EF.CN.1', label: 'E.F. Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_NAME.GH.1', label: 'Nombre Plantel - GeografÃ­a, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_LOCAL.GH.1', label: 'Localidad Plantel - GeografÃ­a, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_EF.GH.1', label: 'E.F. Plantel - GeografÃ­a, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_NAME.CA.2', label: 'Nombre Plantel - Castellano (2)' },
    { value: 'rawData.INST_LOCAL.CA.2', label: 'Localidad Plantel - Castellano (2)' },
    { value: 'rawData.INST_EF.CA.2', label: 'E.F. Plantel - Castellano (2)' },
    { value: 'rawData.INST_NAME.IN.2', label: 'Nombre Plantel - Ingles (2)' },
    { value: 'rawData.INST_LOCAL.IN.2', label: 'Localidad Plantel - Ingles (2)' },
    { value: 'rawData.INST_EF.IN.2', label: 'E.F. Plantel - Ingles (2)' },
    { value: 'rawData.INST_NAME.MA.2', label: 'Nombre Plantel - Matematica (2)' },
    { value: 'rawData.INST_LOCAL.MA.2', label: 'Localidad Plantel - Matematica (2)' },
    { value: 'rawData.INST_EF.MA.2', label: 'E.F. Plantel - Matematica (2)' },
    { value: 'rawData.INST_NAME.EF.2', label: 'Nombre Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_LOCAL.EF.2', label: 'Localidad Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_EF.EF.2', label: 'E.F. Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_NAME.AP.2', label: 'Nombre Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_LOCAL.AP.2', label: 'Localidad Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_EF.AP.2', label: 'E.F. Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_NAME.CN.2', label: 'Nombre Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_LOCAL.CN.2', label: 'Localidad Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_EF.CN.2', label: 'E.F. Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_NAME.GH.2', label: 'Nombre Plantel - GeografÃ­a, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_LOCAL.GH.2', label: 'Localidad Plantel - GeografÃ­a, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_EF.GH.2', label: 'E.F. Plantel - GeografÃ­a, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_NAME.CA.3', label: 'Nombre Plantel - Castellano (3)' },
    { value: 'rawData.INST_LOCAL.CA.3', label: 'Localidad Plantel - Castellano (3)' },
    { value: 'rawData.INST_EF.CA.3', label: 'E.F. Plantel - Castellano (3)' },
    { value: 'rawData.INST_NAME.IN.3', label: 'Nombre Plantel - Ingles (3)' },
    { value: 'rawData.INST_LOCAL.IN.3', label: 'Localidad Plantel - Ingles (3)' },
    { value: 'rawData.INST_EF.IN.3', label: 'E.F. Plantel - Ingles (3)' },
    { value: 'rawData.INST_NAME.MA.3', label: 'Nombre Plantel - Matematica (3)' },
    { value: 'rawData.INST_LOCAL.MA.3', label: 'Localidad Plantel - Matematica (3)' },
    { value: 'rawData.INST_EF.MA.3', label: 'E.F. Plantel - Matematica (3)' },
    { value: 'rawData.INST_NAME.EF.3', label: 'Nombre Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_LOCAL.EF.3', label: 'Localidad Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_EF.EF.3', label: 'E.F. Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_NAME.FI.3', label: 'Nombre Plantel - Fisica (3)' },
    { value: 'rawData.INST_LOCAL.FI.3', label: 'Localidad Plantel - Fisica (3)' },
    { value: 'rawData.INST_EF.FI.3', label: 'E.F. Plantel - Fisica (3)' },
    { value: 'rawData.INST_NAME.QU.3', label: 'Nombre Plantel - Quimica (3)' },
    { value: 'rawData.INST_LOCAL.QU.3', label: 'Localidad Plantel - Quimica (3)' },
    { value: 'rawData.INST_EF.QU.3', label: 'E.F. Plantel - Quimica (3)' },
    { value: 'rawData.INST_NAME.BI.3', label: 'Nombre Plantel - Biologia (3)' },
    { value: 'rawData.INST_LOCAL.BI.3', label: 'Localidad Plantel - Biologia (3)' },
    { value: 'rawData.INST_EF.BI.3', label: 'E.F. Plantel - Biologia (3)' },
    { value: 'rawData.INST_NAME.GH.3', label: 'Nombre Plantel - GeografÃ­a, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_LOCAL.GH.3', label: 'Localidad Plantel - GeografÃ­a, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_EF.GH.3', label: 'E.F. Plantel - GeografÃ­a, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_NAME.CA.4', label: 'Nombre Plantel - Castellano (4)' },
    { value: 'rawData.INST_LOCAL.CA.4', label: 'Localidad Plantel - Castellano (4)' },
    { value: 'rawData.INST_EF.CA.4', label: 'E.F. Plantel - Castellano (4)' },
    { value: 'rawData.INST_NAME.IN.4', label: 'Nombre Plantel - Ingles (4)' },
    { value: 'rawData.INST_LOCAL.IN.4', label: 'Localidad Plantel - Ingles (4)' },
    { value: 'rawData.INST_EF.IN.4', label: 'E.F. Plantel - Ingles (4)' },
    { value: 'rawData.INST_NAME.MA.4', label: 'Nombre Plantel - Matematica (4)' },
    { value: 'rawData.INST_LOCAL.MA.4', label: 'Localidad Plantel - Matematica (4)' },
    { value: 'rawData.INST_EF.MA.4', label: 'E.F. Plantel - Matematica (4)' },
    { value: 'rawData.INST_NAME.EF.4', label: 'Nombre Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_LOCAL.EF.4', label: 'Localidad Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_EF.EF.4', label: 'E.F. Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_NAME.FI.4', label: 'Nombre Plantel - Fisica (4)' },
    { value: 'rawData.INST_LOCAL.FI.4', label: 'Localidad Plantel - Fisica (4)' },
    { value: 'rawData.INST_EF.FI.4', label: 'E.F. Plantel - Fisica (4)' },
    { value: 'rawData.INST_NAME.QU.4', label: 'Nombre Plantel - Quimica (4)' },
    { value: 'rawData.INST_LOCAL.QU.4', label: 'Localidad Plantel - Quimica (4)' },
    { value: 'rawData.INST_EF.QU.4', label: 'E.F. Plantel - Quimica (4)' },
    { value: 'rawData.INST_NAME.BI.4', label: 'Nombre Plantel - Biologia (4)' },
    { value: 'rawData.INST_LOCAL.BI.4', label: 'Localidad Plantel - Biologia (4)' },
    { value: 'rawData.INST_EF.BI.4', label: 'E.F. Plantel - Biologia (4)' },
    { value: 'rawData.INST_NAME.GH.4', label: 'Nombre Plantel - GeografÃ­a, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_LOCAL.GH.4', label: 'Localidad Plantel - GeografÃ­a, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_EF.GH.4', label: 'E.F. Plantel - GeografÃ­a, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_NAME.FS.4', label: 'Nombre Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_LOCAL.FS.4', label: 'Localidad Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_EF.FS.4', label: 'E.F. Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_NAME.CA.5', label: 'Nombre Plantel - Castellano (5)' },
    { value: 'rawData.INST_LOCAL.CA.5', label: 'Localidad Plantel - Castellano (5)' },
    { value: 'rawData.INST_EF.CA.5', label: 'E.F. Plantel - Castellano (5)' },
    { value: 'rawData.INST_NAME.IN.5', label: 'Nombre Plantel - Ingles (5)' },
    { value: 'rawData.INST_LOCAL.IN.5', label: 'Localidad Plantel - Ingles (5)' },
    { value: 'rawData.INST_EF.IN.5', label: 'E.F. Plantel - Ingles (5)' },
    { value: 'rawData.INST_NAME.MA.5', label: 'Nombre Plantel - Matematica (5)' },
    { value: 'rawData.INST_LOCAL.MA.5', label: 'Localidad Plantel - Matematica (5)' },
    { value: 'rawData.INST_EF.MA.5', label: 'E.F. Plantel - Matematica (5)' },
    { value: 'rawData.INST_NAME.EF.5', label: 'Nombre Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_LOCAL.EF.5', label: 'Localidad Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_EF.EF.5', label: 'E.F. Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_NAME.FI.5', label: 'Nombre Plantel - Fisica (5)' },
    { value: 'rawData.INST_LOCAL.FI.5', label: 'Localidad Plantel - Fisica (5)' },
    { value: 'rawData.INST_EF.FI.5', label: 'E.F. Plantel - Fisica (5)' },
    { value: 'rawData.INST_NAME.QU.5', label: 'Nombre Plantel - Quimica (5)' },
    { value: 'rawData.INST_LOCAL.QU.5', label: 'Localidad Plantel - Quimica (5)' },
    { value: 'rawData.INST_EF.QU.5', label: 'E.F. Plantel - Quimica (5)' },
    { value: 'rawData.INST_NAME.BI.5', label: 'Nombre Plantel - Biologia (5)' },
    { value: 'rawData.INST_LOCAL.BI.5', label: 'Localidad Plantel - Biologia (5)' },
    { value: 'rawData.INST_EF.BI.5', label: 'E.F. Plantel - Biologia (5)' },
    { value: 'rawData.INST_NAME.CT.5', label: 'Nombre Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_LOCAL.CT.5', label: 'Localidad Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_EF.CT.5', label: 'E.F. Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_NAME.GH.5', label: 'Nombre Plantel - GeografÃ­a, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_LOCAL.GH.5', label: 'Localidad Plantel - GeografÃ­a, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_EF.GH.5', label: 'E.F. Plantel - GeografÃ­a, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_NAME.FS.5', label: 'Nombre Plantel - Form. para la Sober. Nal. (5)' },
    { value: 'rawData.INST_LOCAL.FS.5', label: 'Localidad Plantel - Form. para la Sober. Nal. (5)' },
    { value: 'rawData.INST_EF.FS.5', label: 'E.F. Plantel - Form. para la Sober. Nal. (5)' }
  ]}
]

export const DATA_BINDINGS_DEROGADO: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Datos Personales', bindings: [
    { value: 'rawData.CEDULA', label: 'CÃ©dula' },
    { value: 'rawData.FECHA', label: 'Fecha' },
    { value: 'rawData.APELLIDOS', label: 'Apellidos' },
    { value: 'rawData.NOMBRES', label: 'Nombres' },
    { value: 'rawData.PAIS', label: 'PaÃ­s' },
    { value: 'rawData.ESTADO', label: 'Estado' },
    { value: 'rawData.MUNICIPIO', label: 'Municipio' },
    { value: 'rawData.LUGAR', label: 'Lugar' },
    { value: 'rawData.PROMEDIO.BASICA', label: 'Promedio AcadÃ©mico BÃ¡sica' },
    { value: 'rawData.PROMEDIO.DIVERSIFICADO', label: 'Promedio AcadÃ©mico Diversificado' },
    { value: 'expedicion.fecha', label: 'Fecha de ExpediciÃ³n (Z4 / hoy)' },
    { value: 'expedicion.lugar', label: 'Lugar de ExpediciÃ³n (AH4 / MIRANDA)' },
    { value: 'director.nombre', label: 'Nombre del Director (Z6)' },
    { value: 'director.cedula', label: 'CÃ©dula del Director (Z7)' },
  ]},
  { group: 'EducaciÃ³n BÃ¡sica', bindings: [
    { value: 'rawData.INST.BASICA.1', label: 'InstituciÃ³n BÃ¡sica 1' },
    { value: 'rawData.LOCAL.BASICA.1', label: 'Localidad BÃ¡sica 1' },
    { value: 'rawData.EF.BASICA.1', label: 'E.F. BÃ¡sica 1' },
    { value: 'rawData.INST.BASICA.2', label: 'InstituciÃ³n BÃ¡sica 2' },
    { value: 'rawData.LOCAL.BASICA.2', label: 'Localidad BÃ¡sica 2' },
    { value: 'rawData.EF.BASICA.2', label: 'E.F. BÃ¡sica 2' },
    { value: 'rawData.INST.BASICA.3', label: 'InstituciÃ³n BÃ¡sica 3' },
    { value: 'rawData.LOCAL.BASICA.3', label: 'Localidad BÃ¡sica 3' },
    { value: 'rawData.EF.BASICA.3', label: 'E.F. BÃ¡sica 3' },
    { value: 'rawData.INST.BASICA.4', label: 'InstituciÃ³n BÃ¡sica 4' },
    { value: 'rawData.LOCAL.BASICA.4', label: 'Localidad BÃ¡sica 4' },
    { value: 'rawData.EF.BASICA.4', label: 'E.F. BÃ¡sica 4' },
    { value: 'rawData.INST.BASICA.5', label: 'InstituciÃ³n BÃ¡sica 5' },
    { value: 'rawData.LOCAL.BASICA.5', label: 'Localidad BÃ¡sica 5' },
    { value: 'rawData.EF.BASICA.5', label: 'E.F. BÃ¡sica 5' },
    { value: 'rawData.OBS.BASICA.L1', label: 'Obs. BÃ¡sica â€” LÃ­nea 1' },
    { value: 'rawData.OBS.BASICA.L2', label: 'Obs. BÃ¡sica â€” LÃ­nea 2' },
    { value: 'rawData.OBS.BASICA.L3', label: 'Obs. BÃ¡sica â€” LÃ­nea 3' },
    { value: 'rawData.OBS.BASICA.L4', label: 'Obs. BÃ¡sica â€” LÃ­nea 4' },
    { value: 'rawData.OBS.BASICA.L5', label: 'Obs. BÃ¡sica â€” LÃ­nea 5' },
  ]},
  { group: 'Diversificado', bindings: [
    { value: 'rawData.INST.DIV.1', label: 'InstituciÃ³n Diversificado 1' },
    { value: 'rawData.LOCAL.DIV.1', label: 'Localidad Diversificado 1' },
    { value: 'rawData.EF.DIV.1', label: 'E.F. Diversificado 1' },
    { value: 'rawData.INST.DIV.2', label: 'InstituciÃ³n Diversificado 2' },
    { value: 'rawData.LOCAL.DIV.2', label: 'Localidad Diversificado 2' },
    { value: 'rawData.EF.DIV.2', label: 'E.F. Diversificado 2' },
    { value: 'rawData.INST.DIV.3', label: 'InstituciÃ³n Diversificado 3' },
    { value: 'rawData.LOCAL.DIV.3', label: 'Localidad Diversificado 3' },
    { value: 'rawData.EF.DIV.3', label: 'E.F. Diversificado 3' },
    { value: 'rawData.INST.DIV.4', label: 'InstituciÃ³n Diversificado 4' },
    { value: 'rawData.LOCAL.DIV.4', label: 'Localidad Diversificado 4' },
    { value: 'rawData.EF.DIV.4', label: 'E.F. Diversificado 4' },
    { value: 'rawData.INST.DIV.5', label: 'InstituciÃ³n Diversificado 5' },
    { value: 'rawData.LOCAL.DIV.5', label: 'Localidad Diversificado 5' },
    { value: 'rawData.EF.DIV.5', label: 'E.F. Diversificado 5' },
  ]},
  { group: 'Calificaciones', bindings: [
    { value: 'rawData.NOTA.CA.1', label: 'Primer AÃ±o â€” Castellano â€” Nota' },
    { value: 'rawData.LITERAL.CA.1', label: 'Primer AÃ±o â€” Castellano â€” Literal' },
    { value: 'rawData.EVAL.CA.1', label: 'Primer AÃ±o â€” Castellano â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.CA.1', label: 'Primer AÃ±o â€” Castellano â€” Mes' },
    { value: 'rawData.AÃ‘O.CA.1', label: 'Primer AÃ±o â€” Castellano â€” AÃ±o' },
    { value: 'rawData.INST.CA.1', label: 'Primer AÃ±o â€” Castellano â€” Inst.' },
    { value: 'rawData.NOTA.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” Nota' },
    { value: 'rawData.LITERAL.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” Literal' },
    { value: 'rawData.EVAL.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” Mes' },
    { value: 'rawData.AÃ‘O.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” AÃ±o' },
    { value: 'rawData.INST.IN.1', label: 'Primer AÃ±o â€” InglÃ©s â€” Inst.' },
    { value: 'rawData.NOTA.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” Nota' },
    { value: 'rawData.LITERAL.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” Literal' },
    { value: 'rawData.EVAL.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” Mes' },
    { value: 'rawData.AÃ‘O.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” AÃ±o' },
    { value: 'rawData.INST.MA.1', label: 'Primer AÃ±o â€” MatemÃ¡ticas â€” Inst.' },
    { value: 'rawData.NOTA.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” Nota' },
    { value: 'rawData.LITERAL.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” Literal' },
    { value: 'rawData.EVAL.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” Mes' },
    { value: 'rawData.AÃ‘O.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” AÃ±o' },
    { value: 'rawData.INST.EN.1', label: 'Primer AÃ±o â€” Estudios de la Naturaleza â€” Inst.' },
    { value: 'rawData.NOTA.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” Nota' },
    { value: 'rawData.LITERAL.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” Literal' },
    { value: 'rawData.EVAL.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” Mes' },
    { value: 'rawData.AÃ‘O.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” AÃ±o' },
    { value: 'rawData.INST.HV.1', label: 'Primer AÃ±o â€” Historia de Venezuela â€” Inst.' },
    { value: 'rawData.NOTA.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Nota' },
    { value: 'rawData.LITERAL.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Literal' },
    { value: 'rawData.EVAL.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Mes' },
    { value: 'rawData.AÃ‘O.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” AÃ±o' },
    { value: 'rawData.INST.EF.1', label: 'Primer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Inst.' },
    { value: 'rawData.NOTA.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” Nota' },
    { value: 'rawData.LITERAL.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” Literal' },
    { value: 'rawData.EVAL.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” Mes' },
    { value: 'rawData.AÃ‘O.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” AÃ±o' },
    { value: 'rawData.INST.CA.2', label: 'Segundo AÃ±o â€” Castellano â€” Inst.' },
    { value: 'rawData.NOTA.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” Nota' },
    { value: 'rawData.LITERAL.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” Literal' },
    { value: 'rawData.EVAL.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” Mes' },
    { value: 'rawData.AÃ‘O.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” AÃ±o' },
    { value: 'rawData.INST.IN.2', label: 'Segundo AÃ±o â€” InglÃ©s â€” Inst.' },
    { value: 'rawData.NOTA.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” Nota' },
    { value: 'rawData.LITERAL.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” Literal' },
    { value: 'rawData.EVAL.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” Mes' },
    { value: 'rawData.AÃ‘O.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” AÃ±o' },
    { value: 'rawData.INST.MA.2', label: 'Segundo AÃ±o â€” MatemÃ¡ticas â€” Inst.' },
    { value: 'rawData.NOTA.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” Nota' },
    { value: 'rawData.LITERAL.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” Literal' },
    { value: 'rawData.EVAL.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” Mes' },
    { value: 'rawData.AÃ‘O.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” AÃ±o' },
    { value: 'rawData.INST.EN.2', label: 'Segundo AÃ±o â€” Estudios de la Naturaleza â€” Inst.' },
    { value: 'rawData.NOTA.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” Nota' },
    { value: 'rawData.LITERAL.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” Literal' },
    { value: 'rawData.EVAL.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” Mes' },
    { value: 'rawData.AÃ‘O.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” AÃ±o' },
    { value: 'rawData.INST.HV.2', label: 'Segundo AÃ±o â€” Historia de Venezuela â€” Inst.' },
    { value: 'rawData.NOTA.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” Nota' },
    { value: 'rawData.LITERAL.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” Literal' },
    { value: 'rawData.EVAL.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” Mes' },
    { value: 'rawData.AÃ‘O.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” AÃ±o' },
    { value: 'rawData.INST.EF.2', label: 'Segundo AÃ±o â€” EducaciÃ³n FÃ­sica â€” Inst.' },
    { value: 'rawData.NOTA.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” Nota' },
    { value: 'rawData.LITERAL.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” Literal' },
    { value: 'rawData.EVAL.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” Mes' },
    { value: 'rawData.AÃ‘O.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” AÃ±o' },
    { value: 'rawData.INST.CA.3', label: 'Tercer AÃ±o â€” Castellano â€” Inst.' },
    { value: 'rawData.NOTA.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” Nota' },
    { value: 'rawData.LITERAL.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” Literal' },
    { value: 'rawData.EVAL.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” Mes' },
    { value: 'rawData.AÃ‘O.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” AÃ±o' },
    { value: 'rawData.INST.IN.3', label: 'Tercer AÃ±o â€” InglÃ©s â€” Inst.' },
    { value: 'rawData.NOTA.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” Nota' },
    { value: 'rawData.LITERAL.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” Literal' },
    { value: 'rawData.EVAL.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” Mes' },
    { value: 'rawData.AÃ‘O.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” AÃ±o' },
    { value: 'rawData.INST.MA.3', label: 'Tercer AÃ±o â€” MatemÃ¡ticas â€” Inst.' },
    { value: 'rawData.NOTA.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” Nota' },
    { value: 'rawData.LITERAL.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” Literal' },
    { value: 'rawData.EVAL.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” Mes' },
    { value: 'rawData.AÃ‘O.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” AÃ±o' },
    { value: 'rawData.INST.EN.3', label: 'Tercer AÃ±o â€” Estudios de la Naturaleza â€” Inst.' },
    { value: 'rawData.NOTA.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” Nota' },
    { value: 'rawData.LITERAL.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” Literal' },
    { value: 'rawData.EVAL.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” Mes' },
    { value: 'rawData.AÃ‘O.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” AÃ±o' },
    { value: 'rawData.INST.HV.3', label: 'Tercer AÃ±o â€” Historia de Venezuela â€” Inst.' },
    { value: 'rawData.NOTA.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Nota' },
    { value: 'rawData.LITERAL.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Literal' },
    { value: 'rawData.EVAL.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Mes' },
    { value: 'rawData.AÃ‘O.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” AÃ±o' },
    { value: 'rawData.INST.EF.3', label: 'Tercer AÃ±o â€” EducaciÃ³n FÃ­sica â€” Inst.' },
    { value: 'rawData.NOTA.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” Nota' },
    { value: 'rawData.LITERAL.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” Literal' },
    { value: 'rawData.EVAL.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” Mes' },
    { value: 'rawData.AÃ‘O.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” AÃ±o' },
    { value: 'rawData.INST.CA.4', label: 'Cuarto AÃ±o â€” Castellano â€” Inst.' },
    { value: 'rawData.NOTA.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” Nota' },
    { value: 'rawData.LITERAL.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” Literal' },
    { value: 'rawData.EVAL.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” Mes' },
    { value: 'rawData.AÃ‘O.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” AÃ±o' },
    { value: 'rawData.INST.IN.4', label: 'Cuarto AÃ±o â€” InglÃ©s â€” Inst.' },
    { value: 'rawData.NOTA.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” Nota' },
    { value: 'rawData.LITERAL.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” Literal' },
    { value: 'rawData.EVAL.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” Mes' },
    { value: 'rawData.AÃ‘O.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” AÃ±o' },
    { value: 'rawData.INST.MA.4', label: 'Cuarto AÃ±o â€” MatemÃ¡ticas â€” Inst.' },
    { value: 'rawData.NOTA.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” Nota' },
    { value: 'rawData.LITERAL.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” Literal' },
    { value: 'rawData.EVAL.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” Mes' },
    { value: 'rawData.AÃ‘O.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” AÃ±o' },
    { value: 'rawData.INST.EN.4', label: 'Cuarto AÃ±o â€” Estudios de la Naturaleza â€” Inst.' },
    { value: 'rawData.NOTA.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” Nota' },
    { value: 'rawData.LITERAL.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” Literal' },
    { value: 'rawData.EVAL.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” Mes' },
    { value: 'rawData.AÃ‘O.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” AÃ±o' },
    { value: 'rawData.INST.HV.4', label: 'Cuarto AÃ±o â€” Historia de Venezuela â€” Inst.' },
    { value: 'rawData.NOTA.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Nota' },
    { value: 'rawData.LITERAL.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Literal' },
    { value: 'rawData.EVAL.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Mes' },
    { value: 'rawData.AÃ‘O.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” AÃ±o' },
    { value: 'rawData.INST.EF.4', label: 'Cuarto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Inst.' },
    { value: 'rawData.NOTA.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” Nota' },
    { value: 'rawData.LITERAL.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” Literal' },
    { value: 'rawData.EVAL.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” Mes' },
    { value: 'rawData.AÃ‘O.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” AÃ±o' },
    { value: 'rawData.INST.CA.5', label: 'Quinto AÃ±o â€” Castellano â€” Inst.' },
    { value: 'rawData.NOTA.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” Nota' },
    { value: 'rawData.LITERAL.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” Literal' },
    { value: 'rawData.EVAL.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” Mes' },
    { value: 'rawData.AÃ‘O.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” AÃ±o' },
    { value: 'rawData.INST.IN.5', label: 'Quinto AÃ±o â€” InglÃ©s â€” Inst.' },
    { value: 'rawData.NOTA.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” Nota' },
    { value: 'rawData.LITERAL.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” Literal' },
    { value: 'rawData.EVAL.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” Mes' },
    { value: 'rawData.AÃ‘O.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” AÃ±o' },
    { value: 'rawData.INST.MA.5', label: 'Quinto AÃ±o â€” MatemÃ¡ticas â€” Inst.' },
    { value: 'rawData.NOTA.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” Nota' },
    { value: 'rawData.LITERAL.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” Literal' },
    { value: 'rawData.EVAL.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” Mes' },
    { value: 'rawData.AÃ‘O.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” AÃ±o' },
    { value: 'rawData.INST.EN.5', label: 'Quinto AÃ±o â€” Estudios de la Naturaleza â€” Inst.' },
    { value: 'rawData.NOTA.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” Nota' },
    { value: 'rawData.LITERAL.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” Literal' },
    { value: 'rawData.EVAL.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” Mes' },
    { value: 'rawData.AÃ‘O.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” AÃ±o' },
    { value: 'rawData.INST.HV.5', label: 'Quinto AÃ±o â€” Historia de Venezuela â€” Inst.' },
    { value: 'rawData.NOTA.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Nota' },
    { value: 'rawData.LITERAL.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Literal' },
    { value: 'rawData.EVAL.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” EvaluaciÃ³n' },
    { value: 'rawData.MES.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Mes' },
    { value: 'rawData.AÃ‘O.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” AÃ±o' },
    { value: 'rawData.INST.EF.5', label: 'Quinto AÃ±o â€” EducaciÃ³n FÃ­sica â€” Inst.' },
  ]},
,
  { group: 'Plantel por Materia (Constancia)', bindings: [
    { value: 'rawData.INST_NAME.CA.1', label: 'Nombre Plantel - Castellano (1)' },
    { value: 'rawData.INST_LOCAL.CA.1', label: 'Localidad Plantel - Castellano (1)' },
    { value: 'rawData.INST_EF.CA.1', label: 'E.F. Plantel - Castellano (1)' },
    { value: 'rawData.INST_NAME.CA.2', label: 'Nombre Plantel - Castellano (2)' },
    { value: 'rawData.INST_LOCAL.CA.2', label: 'Localidad Plantel - Castellano (2)' },
    { value: 'rawData.INST_EF.CA.2', label: 'E.F. Plantel - Castellano (2)' },
    { value: 'rawData.INST_NAME.CA.3', label: 'Nombre Plantel - Castellano (3)' },
    { value: 'rawData.INST_LOCAL.CA.3', label: 'Localidad Plantel - Castellano (3)' },
    { value: 'rawData.INST_EF.CA.3', label: 'E.F. Plantel - Castellano (3)' },
    { value: 'rawData.INST_NAME.CA.4', label: 'Nombre Plantel - Castellano (4)' },
    { value: 'rawData.INST_LOCAL.CA.4', label: 'Localidad Plantel - Castellano (4)' },
    { value: 'rawData.INST_EF.CA.4', label: 'E.F. Plantel - Castellano (4)' },
    { value: 'rawData.INST_NAME.CA.5', label: 'Nombre Plantel - Castellano (5)' },
    { value: 'rawData.INST_LOCAL.CA.5', label: 'Localidad Plantel - Castellano (5)' },
    { value: 'rawData.INST_EF.CA.5', label: 'E.F. Plantel - Castellano (5)' },
  ]}
]
