// === Helper: generate calif bindings for vigente plan ===
const YEAR_NAMES = ['Primer Año', 'Segundo Año', 'Tercer Año', 'Cuarto Año', 'Quinto Año']
const MATERIAS_VIGENTE: Record<number, string[]> = {
  1: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Arte y Patrimonio', 'Ciencias Naturales', 'Geografía, Historia y Ciudadanía'],
  2: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Arte y Patrimonio', 'Ciencias Naturales', 'Geografía, Historia y Ciudadanía'],
  3: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
  4: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
  5: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Ciencias de la Tierra', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
}

function generateCalifBindings() {
  const groups: { group: string; bindings: { value: string; label: string }[] }[] = []
  for (let y = 1; y <= 5; y++) {
    const materias = MATERIAS_VIGENTE[y] || []
    const bindings: { value: string; label: string }[] = []
    for (let s = 0; s < materias.length; s++) {
      const nombre = materias[s]
      bindings.push(
        { value: `calif.${y}.${s}.materia`, label: `${s + 1}. ${nombre}` },
        { value: `calif.${y}.${s}.nota`, label: `${s + 1}. ${nombre} — Nota` },
        { value: `calif.${y}.${s}.literal`, label: `${s + 1}. ${nombre} — Literal` },
        { value: `calif.${y}.${s}.te`, label: `${s + 1}. ${nombre} — T-E` },
        { value: `calif.${y}.${s}.mes`, label: `${s + 1}. ${nombre} — Mes` },
        { value: `calif.${y}.${s}.anio`, label: `${s + 1}. ${nombre} — Año` },
        { value: `calif.${y}.${s}.inst`, label: `${s + 1}. ${nombre} — Inst. Educ.` },
        { value: `calif.${y}.${s}.numero`, label: `${s + 1}. ${nombre} — N°` },
      )
    }
    groups.push({ group: `Calificaciones — ${YEAR_NAMES[y - 1]}`, bindings })
  }
  return groups
}

export const DATA_BINDINGS_VIGENTE: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Estudiante', bindings: [
    { value: 'student.cedula', label: 'Cédula de Identidad' },
    { value: 'student.apellidos', label: 'Apellidos' },
    { value: 'student.nombres', label: 'Nombres' },
    { value: 'student.fechaNacimiento', label: 'Fecha de Nacimiento' },
    { value: 'student.pais', label: 'País de Nacimiento' },
    { value: 'student.estado', label: 'Estado de Nacimiento' },
    { value: 'student.municipio', label: 'Municipio de Nacimiento' },
  ]},
  { group: 'Institución (Escuela)', bindings: [
    { value: 'school.codigo', label: 'Código OD' },
    { value: 'school.denominacion', label: 'Denominación' },
    { value: 'school.direccion', label: 'Dirección' },
    { value: 'school.telefono', label: 'Teléfono' },
    { value: 'school.municipio', label: 'Municipio' },
    { value: 'school.estado', label: 'Estado' },
    { value: 'school.cdcce', label: 'CDCEE' },
  ]},
  { group: 'Documento', bindings: [
    { value: 'doc.planEstudio', label: 'Plan de Estudio' },
    { value: 'doc.codigo', label: 'Código Plan' },
    { value: 'doc.lugar', label: 'Lugar' },
    { value: 'doc.fechaExpedicion', label: 'Fecha de Expedición' },
    { value: 'doc.observaciones', label: 'Observaciones' },
    { value: 'doc.promedioAcumulado', label: 'Promedio Acumulado' },
    { value: 'doc.acta', label: 'Acta' },
    { value: 'doc.actaFecha', label: 'Acta — Fecha' },
    { value: 'doc.actaAnio', label: 'Acta — Año' },
  ]},
  { group: 'Observaciones Certificación', bindings: [
    { value: 'obsCert.0', label: 'OBS.CERT — Línea 1' },
    { value: 'obsCert.1', label: 'OBS.CERT — Línea 2' },
    { value: 'obsCert.2', label: 'OBS.CERT — Línea 3' },
    { value: 'obsCert.3', label: 'OBS.CERT — Línea 4' },
  ]},
  { group: 'Literales Finales', bindings: [
    { value: 'doc.literalFinal.0', label: 'Literal Final — 1er Año' },
    { value: 'doc.literalFinal.1', label: 'Literal Final — 2do Año' },
    { value: 'doc.literalFinal.2', label: 'Literal Final — 3er Año' },
    { value: 'doc.literalFinal.3', label: 'Literal Final — 4to Año' },
    { value: 'doc.literalFinal.4', label: 'Literal Final — 5to Año' },
  ]},
  { group: 'Director', bindings: [
    { value: 'director.nombre', label: 'Nombre del Director' },
    { value: 'director.cedula', label: 'Cédula del Director' },
  ]},
  { group: 'Director CDCEE', bindings: [
    { value: 'cdcee.nombre', label: 'Nombre Director CDCEE' },
    { value: 'cdcee.cedula', label: 'Cédula Director CDCEE' },
  ]},
  { group: 'Instituciones Educativas', bindings: [
    { value: 'inst.0.denominacion', label: 'Institución 1 — Denominación' },
    { value: 'inst.0.localidad', label: 'Institución 1 — Localidad' },
    { value: 'inst.0.ef', label: 'Institución 1 — E.F.' },
    { value: 'inst.1.denominacion', label: 'Institución 2 — Denominación' },
    { value: 'inst.1.localidad', label: 'Institución 2 — Localidad' },
    { value: 'inst.1.ef', label: 'Institución 2 — E.F.' },
    { value: 'inst.2.denominacion', label: 'Institución 3 — Denominación' },
    { value: 'inst.2.localidad', label: 'Institución 3 — Localidad' },
    { value: 'inst.2.ef', label: 'Institución 3 — E.F.' },
    { value: 'inst.3.denominacion', label: 'Institución 4 — Denominación' },
    { value: 'inst.3.localidad', label: 'Institución 4 — Localidad' },
    { value: 'inst.3.ef', label: 'Institución 4 — E.F.' },
    { value: 'inst.4.denominacion', label: 'Institución 5 — Denominación' },
    { value: 'inst.4.localidad', label: 'Institución 5 — Localidad' },
    { value: 'inst.4.ef', label: 'Institución 5 — E.F.' },
  ]},
  ...generateCalifBindings(),
  { group: 'Orientación y Convivencia', bindings: [
    { value: 'orient.0.anio', label: '1er Año — Año Escolar' },
    { value: 'orient.0.literal', label: '1er Año — Literal' },
    { value: 'orient.1.anio', label: '2do Año — Año Escolar' },
    { value: 'orient.1.literal', label: '2do Año — Literal' },
    { value: 'orient.2.anio', label: '3er Año — Año Escolar' },
    { value: 'orient.2.literal', label: '3er Año — Literal' },
    { value: 'orient.3.anio', label: '4to Año — Año Escolar' },
    { value: 'orient.3.literal', label: '4to Año — Literal' },
    { value: 'orient.4.anio', label: '5to Año — Año Escolar' },
    { value: 'orient.4.literal', label: '5to Año — Literal' },
  ]},
  { group: 'Grupos (Creación/Recreación)', bindings: [
    { value: 'grupo.0.anio', label: '1er Año — Año Escolar' },
    { value: 'grupo.0.grupo', label: '1er Año — Nombre Grupo' },
    { value: 'grupo.0.literal', label: '1er Año — Literal' },
    { value: 'grupo.1.anio', label: '2do Año — Año Escolar' },
    { value: 'grupo.1.grupo', label: '2do Año — Nombre Grupo' },
    { value: 'grupo.1.literal', label: '2do Año — Literal' },
    { value: 'grupo.2.anio', label: '3er Año — Año Escolar' },
    { value: 'grupo.2.grupo', label: '3er Año — Nombre Grupo' },
    { value: 'grupo.2.literal', label: '3er Año — Literal' },
    { value: 'grupo.3.anio', label: '4to Año — Año Escolar' },
    { value: 'grupo.3.grupo', label: '4to Año — Nombre Grupo' },
    { value: 'grupo.3.literal', label: '4to Año — Literal' },
    { value: 'grupo.4.anio', label: '5to Año — Año Escolar' },
    { value: 'grupo.4.grupo', label: '5to Año — Nombre Grupo' },
    { value: 'grupo.4.literal', label: '5to Año — Literal' },
  ]},
]

export const DATA_BINDINGS_DEROGADO: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Datos Personales', bindings: [
    { value: 'rawData.CEDULA', label: 'Cédula' },
    { value: 'rawData.FECHA', label: 'Fecha' },
    { value: 'rawData.APELLIDOS', label: 'Apellidos' },
    { value: 'rawData.NOMBRES', label: 'Nombres' },
    { value: 'rawData.PAIS', label: 'País' },
    { value: 'rawData.ESTADO', label: 'Estado' },
    { value: 'rawData.MUNICIPIO', label: 'Municipio' },
    { value: 'rawData.LUGAR', label: 'Lugar' },
    { value: 'rawData.PROMEDIO.BASICA', label: 'Promedio Académico Básica' },
    { value: 'rawData.PROMEDIO.DIVERSIFICADO', label: 'Promedio Académico Diversificado' },
    { value: 'expedicion.fecha', label: 'Fecha de Expedición (Z4 / hoy)' },
    { value: 'expedicion.lugar', label: 'Lugar de Expedición (AH4 / MIRANDA)' },
    { value: 'director.nombre', label: 'Nombre del Director (Z6)' },
    { value: 'director.cedula', label: 'Cédula del Director (Z7)' },
  ]},
  { group: 'Educación Básica', bindings: [
    { value: 'rawData.INST.BASICA.1', label: 'Institución Básica 1' },
    { value: 'rawData.LOCAL.BASICA.1', label: 'Localidad Básica 1' },
    { value: 'rawData.EF.BASICA.1', label: 'E.F. Básica 1' },
    { value: 'rawData.INST.BASICA.2', label: 'Institución Básica 2' },
    { value: 'rawData.LOCAL.BASICA.2', label: 'Localidad Básica 2' },
    { value: 'rawData.EF.BASICA.2', label: 'E.F. Básica 2' },
    { value: 'rawData.INST.BASICA.3', label: 'Institución Básica 3' },
    { value: 'rawData.LOCAL.BASICA.3', label: 'Localidad Básica 3' },
    { value: 'rawData.EF.BASICA.3', label: 'E.F. Básica 3' },
    { value: 'rawData.INST.BASICA.4', label: 'Institución Básica 4' },
    { value: 'rawData.LOCAL.BASICA.4', label: 'Localidad Básica 4' },
    { value: 'rawData.EF.BASICA.4', label: 'E.F. Básica 4' },
    { value: 'rawData.INST.BASICA.5', label: 'Institución Básica 5' },
    { value: 'rawData.LOCAL.BASICA.5', label: 'Localidad Básica 5' },
    { value: 'rawData.EF.BASICA.5', label: 'E.F. Básica 5' },
    { value: 'rawData.OBS.BASICA.L1', label: 'Obs. Básica — Línea 1' },
    { value: 'rawData.OBS.BASICA.L2', label: 'Obs. Básica — Línea 2' },
    { value: 'rawData.OBS.BASICA.L3', label: 'Obs. Básica — Línea 3' },
    { value: 'rawData.OBS.BASICA.L4', label: 'Obs. Básica — Línea 4' },
    { value: 'rawData.OBS.BASICA.L5', label: 'Obs. Básica — Línea 5' },
  ]},
  { group: 'Diversificado', bindings: [
    { value: 'rawData.INST.DIV.1', label: 'Institución Diversificado 1' },
    { value: 'rawData.LOCAL.DIV.1', label: 'Localidad Diversificado 1' },
    { value: 'rawData.EF.DIV.1', label: 'E.F. Diversificado 1' },
    { value: 'rawData.INST.DIV.2', label: 'Institución Diversificado 2' },
    { value: 'rawData.LOCAL.DIV.2', label: 'Localidad Diversificado 2' },
    { value: 'rawData.EF.DIV.2', label: 'E.F. Diversificado 2' },
    { value: 'rawData.INST.DIV.3', label: 'Institución Diversificado 3' },
    { value: 'rawData.LOCAL.DIV.3', label: 'Localidad Diversificado 3' },
    { value: 'rawData.EF.DIV.3', label: 'E.F. Diversificado 3' },
    { value: 'rawData.INST.DIV.4', label: 'Institución Diversificado 4' },
    { value: 'rawData.LOCAL.DIV.4', label: 'Localidad Diversificado 4' },
    { value: 'rawData.EF.DIV.4', label: 'E.F. Diversificado 4' },
    { value: 'rawData.INST.DIV.5', label: 'Institución Diversificado 5' },
    { value: 'rawData.LOCAL.DIV.5', label: 'Localidad Diversificado 5' },
    { value: 'rawData.EF.DIV.5', label: 'E.F. Diversificado 5' },
  ]},
  { group: 'Calificaciones', bindings: [
    { value: 'rawData.NOTA.CA.1', label: 'Primer Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.1', label: 'Primer Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.1', label: 'Primer Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.1', label: 'Primer Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.1', label: 'Primer Año — Castellano — Año' },
    { value: 'rawData.INST.CA.1', label: 'Primer Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.1', label: 'Primer Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.1', label: 'Primer Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.1', label: 'Primer Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.1', label: 'Primer Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.1', label: 'Primer Año — Inglés — Año' },
    { value: 'rawData.INST.IN.1', label: 'Primer Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.1', label: 'Primer Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.1', label: 'Primer Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.1', label: 'Primer Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.1', label: 'Primer Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.1', label: 'Primer Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.1', label: 'Primer Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.1', label: 'Primer Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.1', label: 'Primer Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.1', label: 'Primer Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.1', label: 'Primer Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.1', label: 'Primer Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.1', label: 'Primer Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Nota' },
    { value: 'rawData.LITERAL.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Literal' },
    { value: 'rawData.EVAL.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Evaluación' },
    { value: 'rawData.MES.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Mes' },
    { value: 'rawData.AÑO.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Año' },
    { value: 'rawData.INST.EFC.1', label: 'Primer Año — Educación Familiar y Ciudadana — Inst.' },
    { value: 'rawData.NOTA.GG.1', label: 'Primer Año — Geografía General — Nota' },
    { value: 'rawData.LITERAL.GG.1', label: 'Primer Año — Geografía General — Literal' },
    { value: 'rawData.EVAL.GG.1', label: 'Primer Año — Geografía General — Evaluación' },
    { value: 'rawData.MES.GG.1', label: 'Primer Año — Geografía General — Mes' },
    { value: 'rawData.AÑO.GG.1', label: 'Primer Año — Geografía General — Año' },
    { value: 'rawData.INST.GG.1', label: 'Primer Año — Geografía General — Inst.' },
    { value: 'rawData.NOTA.EA.1', label: 'Primer Año — Educación Artística — Nota' },
    { value: 'rawData.LITERAL.EA.1', label: 'Primer Año — Educación Artística — Literal' },
    { value: 'rawData.EVAL.EA.1', label: 'Primer Año — Educación Artística — Evaluación' },
    { value: 'rawData.MES.EA.1', label: 'Primer Año — Educación Artística — Mes' },
    { value: 'rawData.AÑO.EA.1', label: 'Primer Año — Educación Artística — Año' },
    { value: 'rawData.INST.EA.1', label: 'Primer Año — Educación Artística — Inst.' },
    { value: 'rawData.NOTA.EF.1', label: 'Primer Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.1', label: 'Primer Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.1', label: 'Primer Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.1', label: 'Primer Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.1', label: 'Primer Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.1', label: 'Primer Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Nota' },
    { value: 'rawData.LITERAL.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Literal' },
    { value: 'rawData.EVAL.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Evaluación' },
    { value: 'rawData.MES.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Mes' },
    { value: 'rawData.AÑO.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Año' },
    { value: 'rawData.INST.EPT.1', label: 'Primer Año — Educación Para El Trabajo — Inst.' },
    { value: 'rawData.NOTA.CA.2', label: 'Segundo Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.2', label: 'Segundo Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.2', label: 'Segundo Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.2', label: 'Segundo Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.2', label: 'Segundo Año — Castellano — Año' },
    { value: 'rawData.INST.CA.2', label: 'Segundo Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.2', label: 'Segundo Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.2', label: 'Segundo Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.2', label: 'Segundo Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.2', label: 'Segundo Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.2', label: 'Segundo Año — Inglés — Año' },
    { value: 'rawData.INST.IN.2', label: 'Segundo Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.2', label: 'Segundo Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.2', label: 'Segundo Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.2', label: 'Segundo Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.2', label: 'Segundo Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.2', label: 'Segundo Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.2', label: 'Segundo Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EPS.2', label: 'Segundo Año — Educación Para La Salud — Nota' },
    { value: 'rawData.LITERAL.EPS.2', label: 'Segundo Año — Educación Para La Salud — Literal' },
    { value: 'rawData.EVAL.EPS.2', label: 'Segundo Año — Educación Para La Salud — Evaluación' },
    { value: 'rawData.MES.EPS.2', label: 'Segundo Año — Educación Para La Salud — Mes' },
    { value: 'rawData.AÑO.EPS.2', label: 'Segundo Año — Educación Para La Salud — Año' },
    { value: 'rawData.INST.EPS.2', label: 'Segundo Año — Educación Para La Salud — Inst.' },
    { value: 'rawData.NOTA.CB.2', label: 'Segundo Año — Ciencias Biológicas — Nota' },
    { value: 'rawData.LITERAL.CB.2', label: 'Segundo Año — Ciencias Biológicas — Literal' },
    { value: 'rawData.EVAL.CB.2', label: 'Segundo Año — Ciencias Biológicas — Evaluación' },
    { value: 'rawData.MES.CB.2', label: 'Segundo Año — Ciencias Biológicas — Mes' },
    { value: 'rawData.AÑO.CB.2', label: 'Segundo Año — Ciencias Biológicas — Año' },
    { value: 'rawData.INST.CB.2', label: 'Segundo Año — Ciencias Biológicas — Inst.' },
    { value: 'rawData.NOTA.HV.2', label: 'Segundo Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.2', label: 'Segundo Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.2', label: 'Segundo Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.2', label: 'Segundo Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.2', label: 'Segundo Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.2', label: 'Segundo Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.HU.2', label: 'Segundo Año — Historia Universal — Nota' },
    { value: 'rawData.LITERAL.HU.2', label: 'Segundo Año — Historia Universal — Literal' },
    { value: 'rawData.EVAL.HU.2', label: 'Segundo Año — Historia Universal — Evaluación' },
    { value: 'rawData.MES.HU.2', label: 'Segundo Año — Historia Universal — Mes' },
    { value: 'rawData.AÑO.HU.2', label: 'Segundo Año — Historia Universal — Año' },
    { value: 'rawData.INST.HU.2', label: 'Segundo Año — Historia Universal — Inst.' },
    { value: 'rawData.NOTA.EA.2', label: 'Segundo Año — Educación Artística — Nota' },
    { value: 'rawData.LITERAL.EA.2', label: 'Segundo Año — Educación Artística — Literal' },
    { value: 'rawData.EVAL.EA.2', label: 'Segundo Año — Educación Artística — Evaluación' },
    { value: 'rawData.MES.EA.2', label: 'Segundo Año — Educación Artística — Mes' },
    { value: 'rawData.AÑO.EA.2', label: 'Segundo Año — Educación Artística — Año' },
    { value: 'rawData.INST.EA.2', label: 'Segundo Año — Educación Artística — Inst.' },
    { value: 'rawData.NOTA.EF.2', label: 'Segundo Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.2', label: 'Segundo Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.2', label: 'Segundo Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.2', label: 'Segundo Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.2', label: 'Segundo Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.2', label: 'Segundo Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Nota' },
    { value: 'rawData.LITERAL.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Literal' },
    { value: 'rawData.EVAL.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Evaluación' },
    { value: 'rawData.MES.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Mes' },
    { value: 'rawData.AÑO.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Año' },
    { value: 'rawData.INST.ET.2', label: 'Segundo Año — Educación Para El Trabajo — Inst.' },
    { value: 'rawData.NOTA.CA.3', label: 'Tercer Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.3', label: 'Tercer Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.3', label: 'Tercer Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.3', label: 'Tercer Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.3', label: 'Tercer Año — Castellano — Año' },
    { value: 'rawData.INST.CA.3', label: 'Tercer Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.3', label: 'Tercer Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.3', label: 'Tercer Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.3', label: 'Tercer Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.3', label: 'Tercer Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.3', label: 'Tercer Año — Inglés — Año' },
    { value: 'rawData.INST.IN.3', label: 'Tercer Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.3', label: 'Tercer Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.3', label: 'Tercer Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.3', label: 'Tercer Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.3', label: 'Tercer Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.3', label: 'Tercer Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.3', label: 'Tercer Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.CB.3', label: 'Tercer Año — Ciencias Biológicas — Nota' },
    { value: 'rawData.LITERAL.CB.3', label: 'Tercer Año — Ciencias Biológicas — Literal' },
    { value: 'rawData.EVAL.CB.3', label: 'Tercer Año — Ciencias Biológicas — Evaluación' },
    { value: 'rawData.MES.CB.3', label: 'Tercer Año — Ciencias Biológicas — Mes' },
    { value: 'rawData.AÑO.CB.3', label: 'Tercer Año — Ciencias Biológicas — Año' },
    { value: 'rawData.INST.CB.3', label: 'Tercer Año — Ciencias Biológicas — Inst.' },
    { value: 'rawData.NOTA.FI.3', label: 'Tercer Año — Física — Nota' },
    { value: 'rawData.LITERAL.FI.3', label: 'Tercer Año — Física — Literal' },
    { value: 'rawData.EVAL.FI.3', label: 'Tercer Año — Física — Evaluación' },
    { value: 'rawData.MES.FI.3', label: 'Tercer Año — Física — Mes' },
    { value: 'rawData.AÑO.FI.3', label: 'Tercer Año — Física — Año' },
    { value: 'rawData.INST.FI.3', label: 'Tercer Año — Física — Inst.' },
    { value: 'rawData.NOTA.QU.3', label: 'Tercer Año — Química — Nota' },
    { value: 'rawData.LITERAL.QU.3', label: 'Tercer Año — Química — Literal' },
    { value: 'rawData.EVAL.QU.3', label: 'Tercer Año — Química — Evaluación' },
    { value: 'rawData.MES.QU.3', label: 'Tercer Año — Química — Mes' },
    { value: 'rawData.AÑO.QU.3', label: 'Tercer Año — Química — Año' },
    { value: 'rawData.INST.QU.3', label: 'Tercer Año — Química — Inst.' },
    { value: 'rawData.NOTA.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Nota' },
    { value: 'rawData.LITERAL.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Literal' },
    { value: 'rawData.EVAL.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Evaluación' },
    { value: 'rawData.MES.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Mes' },
    { value: 'rawData.AÑO.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Año' },
    { value: 'rawData.INST.HVCB.3', label: 'Tercer Año — Historia de Venezuela-Cátedra Bolivariana — Inst.' },
    { value: 'rawData.NOTA.GV.3', label: 'Tercer Año — Geografía de Venezuela — Nota' },
    { value: 'rawData.LITERAL.GV.3', label: 'Tercer Año — Geografía de Venezuela — Literal' },
    { value: 'rawData.EVAL.GV.3', label: 'Tercer Año — Geografía de Venezuela — Evaluación' },
    { value: 'rawData.MES.GV.3', label: 'Tercer Año — Geografía de Venezuela — Mes' },
    { value: 'rawData.AÑO.GV.3', label: 'Tercer Año — Geografía de Venezuela — Año' },
    { value: 'rawData.INST.GV.3', label: 'Tercer Año — Geografía de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.3', label: 'Tercer Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.3', label: 'Tercer Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.3', label: 'Tercer Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.3', label: 'Tercer Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.3', label: 'Tercer Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.3', label: 'Tercer Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Nota' },
    { value: 'rawData.LITERAL.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Literal' },
    { value: 'rawData.EVAL.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Evaluación' },
    { value: 'rawData.MES.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Mes' },
    { value: 'rawData.AÑO.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Año' },
    { value: 'rawData.INST.ET.3', label: 'Tercer Año — Educación Para El Trabajo — Inst.' },
    { value: 'rawData.NOTA.CA.4', label: 'Cuarto Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.4', label: 'Cuarto Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.4', label: 'Cuarto Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.4', label: 'Cuarto Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.4', label: 'Cuarto Año — Castellano — Año' },
    { value: 'rawData.INST.CA.4', label: 'Cuarto Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.MA.4', label: 'Cuarto Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.4', label: 'Cuarto Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.4', label: 'Cuarto Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.4', label: 'Cuarto Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.4', label: 'Cuarto Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.4', label: 'Cuarto Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.HC.4', label: 'Cuarto Año — Historia Contemporánea — Nota' },
    { value: 'rawData.LITERAL.HC.4', label: 'Cuarto Año — Historia Contemporánea — Literal' },
    { value: 'rawData.EVAL.HC.4', label: 'Cuarto Año — Historia Contemporánea — Evaluación' },
    { value: 'rawData.MES.HC.4', label: 'Cuarto Año — Historia Contemporánea — Mes' },
    { value: 'rawData.AÑO.HC.4', label: 'Cuarto Año — Historia Contemporánea — Año' },
    { value: 'rawData.INST.HC.4', label: 'Cuarto Año — Historia Contemporánea — Inst.' },
    { value: 'rawData.NOTA.IN.4', label: 'Cuarto Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.4', label: 'Cuarto Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.4', label: 'Cuarto Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.4', label: 'Cuarto Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.4', label: 'Cuarto Año — Inglés — Año' },
    { value: 'rawData.INST.IN.4', label: 'Cuarto Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.EF.4', label: 'Cuarto Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.4', label: 'Cuarto Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.4', label: 'Cuarto Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.4', label: 'Cuarto Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.4', label: 'Cuarto Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.4', label: 'Cuarto Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.FI.4', label: 'Cuarto Año — Física — Nota' },
    { value: 'rawData.LITERAL.FI.4', label: 'Cuarto Año — Física — Literal' },
    { value: 'rawData.EVAL.FI.4', label: 'Cuarto Año — Física — Evaluación' },
    { value: 'rawData.MES.FI.4', label: 'Cuarto Año — Física — Mes' },
    { value: 'rawData.AÑO.FI.4', label: 'Cuarto Año — Física — Año' },
    { value: 'rawData.INST.FI.4', label: 'Cuarto Año — Física — Inst.' },
    { value: 'rawData.NOTA.QU.4', label: 'Cuarto Año — Química — Nota' },
    { value: 'rawData.LITERAL.QU.4', label: 'Cuarto Año — Química — Literal' },
    { value: 'rawData.EVAL.QU.4', label: 'Cuarto Año — Química — Evaluación' },
    { value: 'rawData.MES.QU.4', label: 'Cuarto Año — Química — Mes' },
    { value: 'rawData.AÑO.QU.4', label: 'Cuarto Año — Química — Año' },
    { value: 'rawData.INST.QU.4', label: 'Cuarto Año — Química — Inst.' },
    { value: 'rawData.NOTA.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Nota' },
    { value: 'rawData.LITERAL.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Literal' },
    { value: 'rawData.EVAL.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Evaluación' },
    { value: 'rawData.MES.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Mes' },
    { value: 'rawData.AÑO.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Año' },
    { value: 'rawData.INST.BI.4', label: 'Cuarto Año — Ciencias Biológicas — Inst.' },
    { value: 'rawData.NOTA.DT.4', label: 'Cuarto Año — Dibujo Técnico — Nota' },
    { value: 'rawData.LITERAL.DT.4', label: 'Cuarto Año — Dibujo Técnico — Literal' },
    { value: 'rawData.EVAL.DT.4', label: 'Cuarto Año — Dibujo Técnico — Evaluación' },
    { value: 'rawData.MES.DT.4', label: 'Cuarto Año — Dibujo Técnico — Mes' },
    { value: 'rawData.AÑO.DT.4', label: 'Cuarto Año — Dibujo Técnico — Año' },
    { value: 'rawData.INST.DT.4', label: 'Cuarto Año — Dibujo Técnico — Inst.' },
    { value: 'rawData.NOTA.FIL.4', label: 'Cuarto Año — Filosofía — Nota' },
    { value: 'rawData.LITERAL.FIL.4', label: 'Cuarto Año — Filosofía — Literal' },
    { value: 'rawData.EVAL.FIL.4', label: 'Cuarto Año — Filosofía — Evaluación' },
    { value: 'rawData.MES.FIL.4', label: 'Cuarto Año — Filosofía — Mes' },
    { value: 'rawData.AÑO.FIL.4', label: 'Cuarto Año — Filosofía — Año' },
    { value: 'rawData.INST.FIL.4', label: 'Cuarto Año — Filosofía — Inst.' },
    { value: 'rawData.NOTA.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Nota' },
    { value: 'rawData.LITERAL.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Literal' },
    { value: 'rawData.EVAL.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Evaluación' },
    { value: 'rawData.MES.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Mes' },
    { value: 'rawData.AÑO.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Año' },
    { value: 'rawData.INST.IPM.4', label: 'Cuarto Año — Instrucción Pre-Militar — Inst.' },
    { value: 'rawData.NOTA.IN.5', label: 'Quinto Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.5', label: 'Quinto Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.5', label: 'Quinto Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.5', label: 'Quinto Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.5', label: 'Quinto Año — Inglés — Año' },
    { value: 'rawData.INST.IN.5', label: 'Quinto Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.EF.5', label: 'Quinto Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.5', label: 'Quinto Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.5', label: 'Quinto Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.5', label: 'Quinto Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.5', label: 'Quinto Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.5', label: 'Quinto Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Nota' },
    { value: 'rawData.LITERAL.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Literal' },
    { value: 'rawData.EVAL.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Evaluación' },
    { value: 'rawData.MES.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Mes' },
    { value: 'rawData.AÑO.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Año' },
    { value: 'rawData.INST.GEV.5', label: 'Quinto Año — Geografía Económica de Venezuela — Inst.' },
    { value: 'rawData.NOTA.CA.5', label: 'Quinto Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.5', label: 'Quinto Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.5', label: 'Quinto Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.5', label: 'Quinto Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.5', label: 'Quinto Año — Castellano — Año' },
    { value: 'rawData.INST.CA.5', label: 'Quinto Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.MA.5', label: 'Quinto Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.5', label: 'Quinto Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.5', label: 'Quinto Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.5', label: 'Quinto Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.5', label: 'Quinto Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.5', label: 'Quinto Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.FI.5', label: 'Quinto Año — Física — Nota' },
    { value: 'rawData.LITERAL.FI.5', label: 'Quinto Año — Física — Literal' },
    { value: 'rawData.EVAL.FI.5', label: 'Quinto Año — Física — Evaluación' },
    { value: 'rawData.MES.FI.5', label: 'Quinto Año — Física — Mes' },
    { value: 'rawData.AÑO.FI.5', label: 'Quinto Año — Física — Año' },
    { value: 'rawData.INST.FI.5', label: 'Quinto Año — Física — Inst.' },
    { value: 'rawData.NOTA.QU.5', label: 'Quinto Año — Química — Nota' },
    { value: 'rawData.LITERAL.QU.5', label: 'Quinto Año — Química — Literal' },
    { value: 'rawData.EVAL.QU.5', label: 'Quinto Año — Química — Evaluación' },
    { value: 'rawData.MES.QU.5', label: 'Quinto Año — Química — Mes' },
    { value: 'rawData.AÑO.QU.5', label: 'Quinto Año — Química — Año' },
    { value: 'rawData.INST.QU.5', label: 'Quinto Año — Química — Inst.' },
    { value: 'rawData.NOTA.BI.5', label: 'Quinto Año — Ciencias Biológicas — Nota' },
    { value: 'rawData.LITERAL.BI.5', label: 'Quinto Año — Ciencias Biológicas — Literal' },
    { value: 'rawData.EVAL.BI.5', label: 'Quinto Año — Ciencias Biológicas — Evaluación' },
    { value: 'rawData.MES.BI.5', label: 'Quinto Año — Ciencias Biológicas — Mes' },
    { value: 'rawData.AÑO.BI.5', label: 'Quinto Año — Ciencias Biológicas — Año' },
    { value: 'rawData.INST.BI.5', label: 'Quinto Año — Ciencias Biológicas — Inst.' },
    { value: 'rawData.NOTA.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Nota' },
    { value: 'rawData.LITERAL.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Literal' },
    { value: 'rawData.EVAL.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Evaluación' },
    { value: 'rawData.MES.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Mes' },
    { value: 'rawData.AÑO.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Año' },
    { value: 'rawData.INST.CT.5', label: 'Quinto Año — Ciencias de la Tierra — Inst.' },
    { value: 'rawData.NOTA.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Nota' },
    { value: 'rawData.LITERAL.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Literal' },
    { value: 'rawData.EVAL.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Evaluación' },
    { value: 'rawData.MES.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Mes' },
    { value: 'rawData.AÑO.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Año' },
    { value: 'rawData.INST.IPM.5', label: 'Quinto Año — Instrucción Pre-Militar — Inst.' },
  ]},
  { group: 'Secciones', bindings: [
    { value: 'rawData.SECCION.1', label: 'Sección 1' },
    { value: 'rawData.SECCION.2', label: 'Sección 2' },
    { value: 'rawData.SECCION.3', label: 'Sección 3' },
    { value: 'rawData.SECCION.4', label: 'Sección 4' },
    { value: 'rawData.SECCION.5', label: 'Sección 5' },
  ]},
  { group: 'EPT (Educación Para El Trabajo)', bindings: [
    { value: 'rawData.EPT.GRADO.1', label: 'EPT 1 — Grado' },
    { value: 'rawData.EPT.NOMBRE.1', label: 'EPT 1 — Nombre' },
    { value: 'rawData.EPT.HORAS.1', label: 'EPT 1 — Horas' },
    { value: 'rawData.EPT.GRADO.2', label: 'EPT 2 — Grado' },
    { value: 'rawData.EPT.NOMBRE.2', label: 'EPT 2 — Nombre' },
    { value: 'rawData.EPT.HORAS.2', label: 'EPT 2 — Horas' },
    { value: 'rawData.EPT.GRADO.3', label: 'EPT 3 — Grado' },
    { value: 'rawData.EPT.NOMBRE.3', label: 'EPT 3 — Nombre' },
    { value: 'rawData.EPT.HORAS.3', label: 'EPT 3 — Horas' },
    { value: 'rawData.EPT.GRADO.4', label: 'EPT 4 — Grado' },
    { value: 'rawData.EPT.NOMBRE.4', label: 'EPT 4 — Nombre' },
    { value: 'rawData.EPT.HORAS.4', label: 'EPT 4 — Horas' },
    { value: 'rawData.EPT.GRADO.5', label: 'EPT 5 — Grado' },
    { value: 'rawData.EPT.NOMBRE.5', label: 'EPT 5 — Nombre' },
    { value: 'rawData.EPT.HORAS.5', label: 'EPT 5 — Horas' },
    { value: 'rawData.EPT.GRADO.6', label: 'EPT 6 — Grado' },
    { value: 'rawData.EPT.NOMBRE.6', label: 'EPT 6 — Nombre' },
    { value: 'rawData.EPT.HORAS.6', label: 'EPT 6 — Horas' },
    { value: 'rawData.EPT.GRADO.7', label: 'EPT 7 — Grado' },
    { value: 'rawData.EPT.NOMBRE.7', label: 'EPT 7 — Nombre' },
    { value: 'rawData.EPT.HORAS.7', label: 'EPT 7 — Horas' },
    { value: 'rawData.EPT.GRADO.8', label: 'EPT 8 — Grado' },
    { value: 'rawData.EPT.NOMBRE.8', label: 'EPT 8 — Nombre' },
    { value: 'rawData.EPT.HORAS.8', label: 'EPT 8 — Horas' },
    { value: 'rawData.EPT.GRADO.9', label: 'EPT 9 — Grado' },
    { value: 'rawData.EPT.NOMBRE.9', label: 'EPT 9 — Nombre' },
    { value: 'rawData.EPT.HORAS.9', label: 'EPT 9 — Horas' },
    { value: 'rawData.EPT.GRADO.10', label: 'EPT 10 — Grado' },
    { value: 'rawData.EPT.NOMBRE.10', label: 'EPT 10 — Nombre' },
    { value: 'rawData.EPT.HORAS.10', label: 'EPT 10 — Horas' },
    { value: 'rawData.EPT.GRADO.11', label: 'EPT 11 — Grado' },
    { value: 'rawData.EPT.NOMBRE.11', label: 'EPT 11 — Nombre' },
    { value: 'rawData.EPT.HORAS.11', label: 'EPT 11 — Horas' },
    { value: 'rawData.EPT.GRADO.12', label: 'EPT 12 — Grado' },
    { value: 'rawData.EPT.NOMBRE.12', label: 'EPT 12 — Nombre' },
    { value: 'rawData.EPT.HORAS.12', label: 'EPT 12 — Horas' },
  ]},
  { group: 'Validación Título/Notas', bindings: [
    { value: 'rawData.SERIALTITULO', label: 'Serial Título' },
    { value: 'rawData.FECHAEMISIONT', label: 'Fecha Emisión Título' },
    { value: 'rawData.EGRESOAÑO', label: 'Año de Egreso' },
    { value: 'rawData.FECHAEMISIONN', label: 'Fecha Emisión Notas' },
  ]},
  { group: 'Observaciones', bindings: [
    { value: 'rawData.OBS.DIV.L1', label: 'Obs. Diversificado — Línea 1' },
    { value: 'rawData.OBS.DIV.L2', label: 'Obs. Diversificado — Línea 2' },
    { value: 'rawData.OBS.DIV.L3', label: 'Obs. Diversificado — Línea 3' },
    { value: 'rawData.OBS.DIV.L4', label: 'Obs. Diversificado — Línea 4' },
    { value: 'rawData.OBS.DIV.L5', label: 'Obs. Diversificado — Línea 5' },
  ]},
]