// === Helper: generate calif bindings for vigente plan ===
const YEAR_NAMES = ['Primer Año', 'Segundo Año', 'Tercer Año', 'Cuarto Año', 'Quinto Año']
const MATERIAS_VIGENTE: Record<number, string[]> = {
  1: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Arte y Patrimonio', 'Ciencias Naturales', 'Geografía, Historia y Ciudadanía'],
  2: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Arte y Patrimonio', 'Ciencias Naturales', 'Geografía, Historia y Ciudadanía'],
  3: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
  4: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
  5: ['Castellano', 'Inglés', 'Matemáticas', 'Educación Física', 'Física', 'Química', 'Biología', 'Ciencias de la Tierra', 'Geografía, Historia y Ciudadanía', 'Formación Soberanía Nacional'],
}

function generateCalifBindings() {
  const groups: { group: string; bindings: { value: string; label: string }[] }[] = []
  for (let y = 1; y <= 5; y++) {
    const materias = MATERIAS_VIGENTE[y] || []
    const bindings: { value: string; label: string }[] = []
    for (let s = 0; s < materias.length; s++) {
      const nombre = materias[s]
      bindings.push(
        { value: `calif.${y}.${s}.materia`, label: `${s + 1}. ${nombre}` },
        { value: `calif.${y}.${s}.nota`, label: `${s + 1}. ${nombre} — Nota` },
        { value: `calif.${y}.${s}.literal`, label: `${s + 1}. ${nombre} — Literal` },
        { value: `calif.${y}.${s}.te`, label: `${s + 1}. ${nombre} — T-E` },
        { value: `calif.${y}.${s}.mes`, label: `${s + 1}. ${nombre} — Mes` },
        { value: `calif.${y}.${s}.anio`, label: `${s + 1}. ${nombre} — Año` },
        { value: `calif.${y}.${s}.inst`, label: `${s + 1}. ${nombre} — Inst. Educ.` },
        { value: `calif.${y}.${s}.numero`, label: `${s + 1}. ${nombre} — N°` },
      )
    }
    groups.push({ group: `Calificaciones — ${YEAR_NAMES[y - 1]}`, bindings })
  }
  return groups
}

export const DATA_BINDINGS_VIGENTE: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Estudiante', bindings: [
    { value: 'student.cedula', label: 'Cédula de Identidad' },
    { value: 'student.apellidos', label: 'Apellidos' },
    { value: 'student.nombres', label: 'Nombres' },
    { value: 'student.fechaNacimiento', label: 'Fecha de Nacimiento' },
    { value: 'student.pais', label: 'País de Nacimiento' },
    { value: 'student.estado', label: 'Estado de Nacimiento' },
    { value: 'student.municipio', label: 'Municipio de Nacimiento' },
    { value: 'student.lugarFechaNac', label: 'Lugar y Fecha de Nacimiento' },
  ]},
  { group: 'Institución (Escuela)', bindings: [
    { value: 'school.codigo', label: 'Código OD' },
    { value: 'school.denominacion', label: 'Denominación' },
    { value: 'school.direccion', label: 'Dirección' },
    { value: 'school.telefono', label: 'Teléfono' },
    { value: 'school.municipio', label: 'Municipio' },
    { value: 'school.estado', label: 'Estado' },
    { value: 'school.cdcce', label: 'CDCEE' },
  ]},
  { group: 'Documento', bindings: [
    { value: 'doc.planEstudio', label: 'Plan de Estudio' },
    { value: 'doc.codigo', label: 'Código Plan' },
    { value: 'doc.lugar', label: 'Lugar' },
    { value: 'doc.fechaExpedicion', label: 'Fecha de Expedición' },
    { value: 'doc.observaciones', label: 'Observaciones' },
    { value: 'doc.promedioAcumulado', label: 'Promedio Acumulado' },
    { value: 'doc.acta', label: 'Acta' },
    { value: 'doc.actaFecha', label: 'Acta — Fecha' },
    { value: 'doc.actaAnio', label: 'Acta — Año' },
  ]},
  { group: 'Observaciones Certificación', bindings: [
    { value: 'obsCert.0', label: 'OBS.CERT — Línea 1' },
    { value: 'obsCert.1', label: 'OBS.CERT — Línea 2' },
    { value: 'obsCert.2', label: 'OBS.CERT — Línea 3' },
    { value: 'obsCert.3', label: 'OBS.CERT — Línea 4' },
    { value: 'rawData.OBS.NOTAS.L1', label: 'Obs. Notas — Linea 1' },
    { value: 'rawData.OBS.NOTAS.L2', label: 'Obs. Notas — Linea 2' },
    { value: 'rawData.OBS.NOTAS.L3', label: 'Obs. Notas — Linea 3' },
  ]},
  { group: 'Literales Finales', bindings: [
    { value: 'doc.literalFinal.0', label: 'Literal Final — 1er Año' },
    { value: 'doc.literalFinal.1', label: 'Literal Final — 2do Año' },
    { value: 'doc.literalFinal.2', label: 'Literal Final — 3er Año' },
    { value: 'doc.literalFinal.3', label: 'Literal Final — 4to Año' },
    { value: 'doc.literalFinal.4', label: 'Literal Final — 5to Año' },
  ]},
  { group: 'Director', bindings: [
    { value: 'director.nombre', label: 'Nombre del Director (Z6)' },
    { value: 'director.cedula', label: 'Cédula del Director (Z7)' },
    { value: 'expedicion.fecha', label: 'Fecha de Expedición (Z4 / hoy)' },
    { value: 'expedicion.lugar', label: 'Lugar de Expedición (AH4 / MIRANDA)' },
  ]},
  { group: 'Director CDCEE', bindings: [
    { value: 'cdcee.nombre', label: 'Nombre Director CDCEE' },
    { value: 'cdcee.cedula', label: 'Cédula Director CDCEE' },
  ]},
  { group: 'Instituciones Educativas', bindings: [
    { value: 'inst.0.denominacion', label: 'Institución 1 — Denominación' },
    { value: 'inst.0.localidad', label: 'Institución 1 — Localidad' },
    { value: 'inst.0.ef', label: 'Institución 1 — E.F.' },
    { value: 'inst.1.denominacion', label: 'Institución 2 — Denominación' },
    { value: 'inst.1.localidad', label: 'Institución 2 — Localidad' },
    { value: 'inst.1.ef', label: 'Institución 2 — E.F.' },
    { value: 'inst.2.denominacion', label: 'Institución 3 — Denominación' },
    { value: 'inst.2.localidad', label: 'Institución 3 — Localidad' },
    { value: 'inst.2.ef', label: 'Institución 3 — E.F.' },
    { value: 'inst.3.denominacion', label: 'Institución 4 — Denominación' },
    { value: 'inst.3.localidad', label: 'Institución 4 — Localidad' },
    { value: 'inst.3.ef', label: 'Institución 4 — E.F.' },
    { value: 'inst.4.denominacion', label: 'Institución 5 — Denominación' },
    { value: 'inst.4.localidad', label: 'Institución 5 — Localidad' },
    { value: 'inst.4.ef', label: 'Institución 5 — E.F.' },
  ]},
  ...generateCalifBindings(),
  { group: 'Orientación y Convivencia', bindings: [
    { value: 'orient.0.anio', label: '1er Año — Año Escolar' },
    { value: 'orient.0.literal', label: '1er Año — Literal' },
    { value: 'orient.1.anio', label: '2do Año — Año Escolar' },
    { value: 'orient.1.literal', label: '2do Año — Literal' },
    { value: 'orient.2.anio', label: '3er Año — Año Escolar' },
    { value: 'orient.2.literal', label: '3er Año — Literal' },
    { value: 'orient.3.anio', label: '4to Año — Año Escolar' },
    { value: 'orient.3.literal', label: '4to Año — Literal' },
    { value: 'orient.4.anio', label: '5to Año — Año Escolar' },
    { value: 'orient.4.literal', label: '5to Año — Literal' },
  ]},
  { group: 'Grupos (Creación/Recreación)', bindings: [
    { value: 'grupo.0.anio', label: '1er Año — Año Escolar' },
    { value: 'grupo.0.grupo', label: '1er Año — Nombre Grupo' },
    { value: 'grupo.0.literal', label: '1er Año — Literal' },
    { value: 'grupo.1.anio', label: '2do Año — Año Escolar' },
    { value: 'grupo.1.grupo', label: '2do Año — Nombre Grupo' },
    { value: 'grupo.1.literal', label: '2do Año — Literal' },
    { value: 'grupo.2.anio', label: '3er Año — Año Escolar' },
    { value: 'grupo.2.grupo', label: '3er Año — Nombre Grupo' },
    { value: 'grupo.2.literal', label: '3er Año — Literal' },
    { value: 'grupo.3.anio', label: '4to Año — Año Escolar' },
    { value: 'grupo.3.grupo', label: '4to Año — Nombre Grupo' },
    { value: 'grupo.3.literal', label: '4to Año — Literal' },
    { value: 'grupo.4.anio', label: '5to Año — Año Escolar' },
    { value: 'grupo.4.grupo', label: '5to Año — Nombre Grupo' },
    { value: 'grupo.4.literal', label: '5to Año — Literal' },
  ]},
  { group: 'Plantel por Materia (Constancia)', bindings: [
    { value: 'rawData.INST_NAME.CA.1', label: 'Nombre Plantel - Castellano (1)' },
    { value: 'rawData.INST_LOCAL.CA.1', label: 'Localidad Plantel - Castellano (1)' },
    { value: 'rawData.INST_EF.CA.1', label: 'E.F. Plantel - Castellano (1)' },
    { value: 'rawData.INST_NAME.IN.1', label: 'Nombre Plantel - Ingles (1)' },
    { value: 'rawData.INST_LOCAL.IN.1', label: 'Localidad Plantel - Ingles (1)' },
    { value: 'rawData.INST_EF.IN.1', label: 'E.F. Plantel - Ingles (1)' },
    { value: 'rawData.INST_NAME.MA.1', label: 'Nombre Plantel - Matematica (1)' },
    { value: 'rawData.INST_LOCAL.MA.1', label: 'Localidad Plantel - Matematica (1)' },
    { value: 'rawData.INST_EF.MA.1', label: 'E.F. Plantel - Matematica (1)' },
    { value: 'rawData.INST_NAME.EF.1', label: 'Nombre Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_LOCAL.EF.1', label: 'Localidad Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_EF.EF.1', label: 'E.F. Plantel - Educacion Fisica (1)' },
    { value: 'rawData.INST_NAME.AP.1', label: 'Nombre Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_LOCAL.AP.1', label: 'Localidad Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_EF.AP.1', label: 'E.F. Plantel - Arte Plasticas (1)' },
    { value: 'rawData.INST_NAME.CN.1', label: 'Nombre Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_LOCAL.CN.1', label: 'Localidad Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_EF.CN.1', label: 'E.F. Plantel - Ciencias Naturales (1)' },
    { value: 'rawData.INST_NAME.GH.1', label: 'Nombre Plantel - Geografía, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_LOCAL.GH.1', label: 'Localidad Plantel - Geografía, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_EF.GH.1', label: 'E.F. Plantel - Geografía, Hist. y Ciudad. (1)' },
    { value: 'rawData.INST_NAME.CA.2', label: 'Nombre Plantel - Castellano (2)' },
    { value: 'rawData.INST_LOCAL.CA.2', label: 'Localidad Plantel - Castellano (2)' },
    { value: 'rawData.INST_EF.CA.2', label: 'E.F. Plantel - Castellano (2)' },
    { value: 'rawData.INST_NAME.IN.2', label: 'Nombre Plantel - Ingles (2)' },
    { value: 'rawData.INST_LOCAL.IN.2', label: 'Localidad Plantel - Ingles (2)' },
    { value: 'rawData.INST_EF.IN.2', label: 'E.F. Plantel - Ingles (2)' },
    { value: 'rawData.INST_NAME.MA.2', label: 'Nombre Plantel - Matematica (2)' },
    { value: 'rawData.INST_LOCAL.MA.2', label: 'Localidad Plantel - Matematica (2)' },
    { value: 'rawData.INST_EF.MA.2', label: 'E.F. Plantel - Matematica (2)' },
    { value: 'rawData.INST_NAME.EF.2', label: 'Nombre Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_LOCAL.EF.2', label: 'Localidad Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_EF.EF.2', label: 'E.F. Plantel - Educacion Fisica (2)' },
    { value: 'rawData.INST_NAME.AP.2', label: 'Nombre Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_LOCAL.AP.2', label: 'Localidad Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_EF.AP.2', label: 'E.F. Plantel - Arte Plasticas (2)' },
    { value: 'rawData.INST_NAME.CN.2', label: 'Nombre Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_LOCAL.CN.2', label: 'Localidad Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_EF.CN.2', label: 'E.F. Plantel - Ciencias Naturales (2)' },
    { value: 'rawData.INST_NAME.GH.2', label: 'Nombre Plantel - Geografía, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_LOCAL.GH.2', label: 'Localidad Plantel - Geografía, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_EF.GH.2', label: 'E.F. Plantel - Geografía, Hist. y Ciudad. (2)' },
    { value: 'rawData.INST_NAME.CA.3', label: 'Nombre Plantel - Castellano (3)' },
    { value: 'rawData.INST_LOCAL.CA.3', label: 'Localidad Plantel - Castellano (3)' },
    { value: 'rawData.INST_EF.CA.3', label: 'E.F. Plantel - Castellano (3)' },
    { value: 'rawData.INST_NAME.IN.3', label: 'Nombre Plantel - Ingles (3)' },
    { value: 'rawData.INST_LOCAL.IN.3', label: 'Localidad Plantel - Ingles (3)' },
    { value: 'rawData.INST_EF.IN.3', label: 'E.F. Plantel - Ingles (3)' },
    { value: 'rawData.INST_NAME.MA.3', label: 'Nombre Plantel - Matematica (3)' },
    { value: 'rawData.INST_LOCAL.MA.3', label: 'Localidad Plantel - Matematica (3)' },
    { value: 'rawData.INST_EF.MA.3', label: 'E.F. Plantel - Matematica (3)' },
    { value: 'rawData.INST_NAME.EF.3', label: 'Nombre Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_LOCAL.EF.3', label: 'Localidad Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_EF.EF.3', label: 'E.F. Plantel - Educacion Fisica (3)' },
    { value: 'rawData.INST_NAME.FI.3', label: 'Nombre Plantel - Fisica (3)' },
    { value: 'rawData.INST_LOCAL.FI.3', label: 'Localidad Plantel - Fisica (3)' },
    { value: 'rawData.INST_EF.FI.3', label: 'E.F. Plantel - Fisica (3)' },
    { value: 'rawData.INST_NAME.QU.3', label: 'Nombre Plantel - Quimica (3)' },
    { value: 'rawData.INST_LOCAL.QU.3', label: 'Localidad Plantel - Quimica (3)' },
    { value: 'rawData.INST_EF.QU.3', label: 'E.F. Plantel - Quimica (3)' },
    { value: 'rawData.INST_NAME.BI.3', label: 'Nombre Plantel - Biologia (3)' },
    { value: 'rawData.INST_LOCAL.BI.3', label: 'Localidad Plantel - Biologia (3)' },
    { value: 'rawData.INST_EF.BI.3', label: 'E.F. Plantel - Biologia (3)' },
    { value: 'rawData.INST_NAME.GH.3', label: 'Nombre Plantel - Geografía, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_LOCAL.GH.3', label: 'Localidad Plantel - Geografía, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_EF.GH.3', label: 'E.F. Plantel - Geografía, Hist. y Ciudad. (3)' },
    { value: 'rawData.INST_NAME.CA.4', label: 'Nombre Plantel - Castellano (4)' },
    { value: 'rawData.INST_LOCAL.CA.4', label: 'Localidad Plantel - Castellano (4)' },
    { value: 'rawData.INST_EF.CA.4', label: 'E.F. Plantel - Castellano (4)' },
    { value: 'rawData.INST_NAME.IN.4', label: 'Nombre Plantel - Ingles (4)' },
    { value: 'rawData.INST_LOCAL.IN.4', label: 'Localidad Plantel - Ingles (4)' },
    { value: 'rawData.INST_EF.IN.4', label: 'E.F. Plantel - Ingles (4)' },
    { value: 'rawData.INST_NAME.MA.4', label: 'Nombre Plantel - Matematica (4)' },
    { value: 'rawData.INST_LOCAL.MA.4', label: 'Localidad Plantel - Matematica (4)' },
    { value: 'rawData.INST_EF.MA.4', label: 'E.F. Plantel - Matematica (4)' },
    { value: 'rawData.INST_NAME.EF.4', label: 'Nombre Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_LOCAL.EF.4', label: 'Localidad Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_EF.EF.4', label: 'E.F. Plantel - Educacion Fisica (4)' },
    { value: 'rawData.INST_NAME.FI.4', label: 'Nombre Plantel - Fisica (4)' },
    { value: 'rawData.INST_LOCAL.FI.4', label: 'Localidad Plantel - Fisica (4)' },
    { value: 'rawData.INST_EF.FI.4', label: 'E.F. Plantel - Fisica (4)' },
    { value: 'rawData.INST_NAME.QU.4', label: 'Nombre Plantel - Quimica (4)' },
    { value: 'rawData.INST_LOCAL.QU.4', label: 'Localidad Plantel - Quimica (4)' },
    { value: 'rawData.INST_EF.QU.4', label: 'E.F. Plantel - Quimica (4)' },
    { value: 'rawData.INST_NAME.BI.4', label: 'Nombre Plantel - Biologia (4)' },
    { value: 'rawData.INST_LOCAL.BI.4', label: 'Localidad Plantel - Biologia (4)' },
    { value: 'rawData.INST_EF.BI.4', label: 'E.F. Plantel - Biologia (4)' },
    { value: 'rawData.INST_NAME.GH.4', label: 'Nombre Plantel - Geografía, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_LOCAL.GH.4', label: 'Localidad Plantel - Geografía, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_EF.GH.4', label: 'E.F. Plantel - Geografía, Hist. y Ciudad. (4)' },
    { value: 'rawData.INST_NAME.FS.4', label: 'Nombre Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_LOCAL.FS.4', label: 'Localidad Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_EF.FS.4', label: 'E.F. Plantel - Form. para la Sober. Nal. (4)' },
    { value: 'rawData.INST_NAME.CA.5', label: 'Nombre Plantel - Castellano (5)' },
    { value: 'rawData.INST_LOCAL.CA.5', label: 'Localidad Plantel - Castellano (5)' },
    { value: 'rawData.INST_EF.CA.5', label: 'E.F. Plantel - Castellano (5)' },
    { value: 'rawData.INST_NAME.IN.5', label: 'Nombre Plantel - Ingles (5)' },
    { value: 'rawData.INST_LOCAL.IN.5', label: 'Localidad Plantel - Ingles (5)' },
    { value: 'rawData.INST_EF.IN.5', label: 'E.F. Plantel - Ingles (5)' },
    { value: 'rawData.INST_NAME.MA.5', label: 'Nombre Plantel - Matematica (5)' },
    { value: 'rawData.INST_LOCAL.MA.5', label: 'Localidad Plantel - Matematica (5)' },
    { value: 'rawData.INST_EF.MA.5', label: 'E.F. Plantel - Matematica (5)' },
    { value: 'rawData.INST_NAME.EF.5', label: 'Nombre Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_LOCAL.EF.5', label: 'Localidad Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_EF.EF.5', label: 'E.F. Plantel - Educacion Fisica (5)' },
    { value: 'rawData.INST_NAME.FI.5', label: 'Nombre Plantel - Fisica (5)' },
    { value: 'rawData.INST_LOCAL.FI.5', label: 'Localidad Plantel - Fisica (5)' },
    { value: 'rawData.INST_EF.FI.5', label: 'E.F. Plantel - Fisica (5)' },
    { value: 'rawData.INST_NAME.QU.5', label: 'Nombre Plantel - Quimica (5)' },
    { value: 'rawData.INST_LOCAL.QU.5', label: 'Localidad Plantel - Quimica (5)' },
    { value: 'rawData.INST_EF.QU.5', label: 'E.F. Plantel - Quimica (5)' },
    { value: 'rawData.INST_NAME.BI.5', label: 'Nombre Plantel - Biologia (5)' },
    { value: 'rawData.INST_LOCAL.BI.5', label: 'Localidad Plantel - Biologia (5)' },
    { value: 'rawData.INST_EF.BI.5', label: 'E.F. Plantel - Biologia (5)' },
    { value: 'rawData.INST_NAME.CT.5', label: 'Nombre Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_LOCAL.CT.5', label: 'Localidad Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_EF.CT.5', label: 'E.F. Plantel - Ciencias de la Tierra (5)' },
    { value: 'rawData.INST_NAME.GH.5', label: 'Nombre Plantel - Geografía, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_LOCAL.GH.5', label: 'Localidad Plantel - Geografía, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_EF.GH.5', label: 'E.F. Plantel - Geografía, Hist. y Ciudad. (5)' },
    { value: 'rawData.INST_NAME.FS.5', label: 'Nombre Plantel - Form. para la Sober. Nal. (5)' },
    { value: 'rawData.INST_LOCAL.FS.5', label: 'Localidad Plantel - Form. para la Sober. Nal. (5)' },
    { value: 'rawData.INST_EF.FS.5', label: 'E.F. Plantel - Form. para la Sober. Nal. (5)' }
  ]}
]

export const DATA_BINDINGS_DEROGADO: { group: string; bindings: { value: string; label: string }[] }[] = [
  { group: 'Datos Personales', bindings: [
    { value: 'rawData.CEDULA', label: 'Cédula' },
    { value: 'rawData.FECHA', label: 'Fecha' },
    { value: 'rawData.APELLIDOS', label: 'Apellidos' },
    { value: 'rawData.NOMBRES', label: 'Nombres' },
    { value: 'rawData.PAIS', label: 'País' },
    { value: 'rawData.ESTADO', label: 'Estado' },
    { value: 'rawData.MUNICIPIO', label: 'Municipio' },
    { value: 'rawData.LUGAR', label: 'Lugar' },
    { value: 'rawData.PROMEDIO.BASICA', label: 'Promedio Académico Básica' },
    { value: 'rawData.PROMEDIO.DIVERSIFICADO', label: 'Promedio Académico Diversificado' },
    { value: 'expedicion.fecha', label: 'Fecha de Expedición (Z4 / hoy)' },
    { value: 'expedicion.lugar', label: 'Lugar de Expedición (AH4 / MIRANDA)' },
    { value: 'director.nombre', label: 'Nombre del Director (Z6)' },
    { value: 'director.cedula', label: 'Cédula del Director (Z7)' },
  ]},
  { group: 'Educación Básica', bindings: [
    { value: 'rawData.INST.BASICA.1', label: 'Institución Básica 1' },
    { value: 'rawData.LOCAL.BASICA.1', label: 'Localidad Básica 1' },
    { value: 'rawData.EF.BASICA.1', label: 'E.F. Básica 1' },
    { value: 'rawData.INST.BASICA.2', label: 'Institución Básica 2' },
    { value: 'rawData.LOCAL.BASICA.2', label: 'Localidad Básica 2' },
    { value: 'rawData.EF.BASICA.2', label: 'E.F. Básica 2' },
    { value: 'rawData.INST.BASICA.3', label: 'Institución Básica 3' },
    { value: 'rawData.LOCAL.BASICA.3', label: 'Localidad Básica 3' },
    { value: 'rawData.EF.BASICA.3', label: 'E.F. Básica 3' },
    { value: 'rawData.INST.BASICA.4', label: 'Institución Básica 4' },
    { value: 'rawData.LOCAL.BASICA.4', label: 'Localidad Básica 4' },
    { value: 'rawData.EF.BASICA.4', label: 'E.F. Básica 4' },
    { value: 'rawData.INST.BASICA.5', label: 'Institución Básica 5' },
    { value: 'rawData.LOCAL.BASICA.5', label: 'Localidad Básica 5' },
    { value: 'rawData.EF.BASICA.5', label: 'E.F. Básica 5' },
    { value: 'rawData.OBS.BASICA.L1', label: 'Obs. Básica — Línea 1' },
    { value: 'rawData.OBS.BASICA.L2', label: 'Obs. Básica — Línea 2' },
    { value: 'rawData.OBS.BASICA.L3', label: 'Obs. Básica — Línea 3' },
    { value: 'rawData.OBS.BASICA.L4', label: 'Obs. Básica — Línea 4' },
    { value: 'rawData.OBS.BASICA.L5', label: 'Obs. Básica — Línea 5' },
  ]},
  { group: 'Diversificado', bindings: [
    { value: 'rawData.INST.DIV.1', label: 'Institución Diversificado 1' },
    { value: 'rawData.LOCAL.DIV.1', label: 'Localidad Diversificado 1' },
    { value: 'rawData.EF.DIV.1', label: 'E.F. Diversificado 1' },
    { value: 'rawData.INST.DIV.2', label: 'Institución Diversificado 2' },
    { value: 'rawData.LOCAL.DIV.2', label: 'Localidad Diversificado 2' },
    { value: 'rawData.EF.DIV.2', label: 'E.F. Diversificado 2' },
    { value: 'rawData.INST.DIV.3', label: 'Institución Diversificado 3' },
    { value: 'rawData.LOCAL.DIV.3', label: 'Localidad Diversificado 3' },
    { value: 'rawData.EF.DIV.3', label: 'E.F. Diversificado 3' },
    { value: 'rawData.INST.DIV.4', label: 'Institución Diversificado 4' },
    { value: 'rawData.LOCAL.DIV.4', label: 'Localidad Diversificado 4' },
    { value: 'rawData.EF.DIV.4', label: 'E.F. Diversificado 4' },
    { value: 'rawData.INST.DIV.5', label: 'Institución Diversificado 5' },
    { value: 'rawData.LOCAL.DIV.5', label: 'Localidad Diversificado 5' },
    { value: 'rawData.EF.DIV.5', label: 'E.F. Diversificado 5' },
  ]},
  { group: 'Calificaciones', bindings: [
    { value: 'rawData.NOTA.CA.1', label: 'Primer Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.1', label: 'Primer Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.1', label: 'Primer Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.1', label: 'Primer Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.1', label: 'Primer Año — Castellano — Año' },
    { value: 'rawData.INST.CA.1', label: 'Primer Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.1', label: 'Primer Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.1', label: 'Primer Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.1', label: 'Primer Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.1', label: 'Primer Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.1', label: 'Primer Año — Inglés — Año' },
    { value: 'rawData.INST.IN.1', label: 'Primer Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.1', label: 'Primer Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.1', label: 'Primer Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.1', label: 'Primer Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.1', label: 'Primer Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.1', label: 'Primer Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.1', label: 'Primer Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.1', label: 'Primer Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.1', label: 'Primer Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.1', label: 'Primer Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.1', label: 'Primer Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.1', label: 'Primer Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.1', label: 'Primer Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.1', label: 'Primer Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.1', label: 'Primer Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.1', label: 'Primer Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.1', label: 'Primer Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.1', label: 'Primer Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.1', label: 'Primer Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.1', label: 'Primer Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.CA.2', label: 'Segundo Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.2', label: 'Segundo Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.2', label: 'Segundo Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.2', label: 'Segundo Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.2', label: 'Segundo Año — Castellano — Año' },
    { value: 'rawData.INST.CA.2', label: 'Segundo Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.2', label: 'Segundo Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.2', label: 'Segundo Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.2', label: 'Segundo Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.2', label: 'Segundo Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.2', label: 'Segundo Año — Inglés — Año' },
    { value: 'rawData.INST.IN.2', label: 'Segundo Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.2', label: 'Segundo Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.2', label: 'Segundo Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.2', label: 'Segundo Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.2', label: 'Segundo Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.2', label: 'Segundo Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.2', label: 'Segundo Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.2', label: 'Segundo Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.2', label: 'Segundo Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.2', label: 'Segundo Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.2', label: 'Segundo Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.2', label: 'Segundo Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.2', label: 'Segundo Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.2', label: 'Segundo Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.2', label: 'Segundo Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.2', label: 'Segundo Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.2', label: 'Segundo Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.2', label: 'Segundo Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.2', label: 'Segundo Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.2', label: 'Segundo Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.CA.3', label: 'Tercer Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.3', label: 'Tercer Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.3', label: 'Tercer Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.3', label: 'Tercer Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.3', label: 'Tercer Año — Castellano — Año' },
    { value: 'rawData.INST.CA.3', label: 'Tercer Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.3', label: 'Tercer Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.3', label: 'Tercer Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.3', label: 'Tercer Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.3', label: 'Tercer Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.3', label: 'Tercer Año — Inglés — Año' },
    { value: 'rawData.INST.IN.3', label: 'Tercer Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.3', label: 'Tercer Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.3', label: 'Tercer Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.3', label: 'Tercer Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.3', label: 'Tercer Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.3', label: 'Tercer Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.3', label: 'Tercer Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.3', label: 'Tercer Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.3', label: 'Tercer Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.3', label: 'Tercer Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.3', label: 'Tercer Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.3', label: 'Tercer Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.3', label: 'Tercer Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.3', label: 'Tercer Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.3', label: 'Tercer Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.3', label: 'Tercer Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.3', label: 'Tercer Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.3', label: 'Tercer Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.3', label: 'Tercer Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.3', label: 'Tercer Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.CA.4', label: 'Cuarto Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.4', label: 'Cuarto Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.4', label: 'Cuarto Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.4', label: 'Cuarto Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.4', label: 'Cuarto Año — Castellano — Año' },
    { value: 'rawData.INST.CA.4', label: 'Cuarto Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.4', label: 'Cuarto Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.4', label: 'Cuarto Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.4', label: 'Cuarto Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.4', label: 'Cuarto Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.4', label: 'Cuarto Año — Inglés — Año' },
    { value: 'rawData.INST.IN.4', label: 'Cuarto Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.4', label: 'Cuarto Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.4', label: 'Cuarto Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.4', label: 'Cuarto Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.4', label: 'Cuarto Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.4', label: 'Cuarto Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.4', label: 'Cuarto Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.4', label: 'Cuarto Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.4', label: 'Cuarto Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.4', label: 'Cuarto Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.4', label: 'Cuarto Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.4', label: 'Cuarto Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.4', label: 'Cuarto Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.4', label: 'Cuarto Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.4', label: 'Cuarto Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.4', label: 'Cuarto Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.4', label: 'Cuarto Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.4', label: 'Cuarto Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.4', label: 'Cuarto Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.4', label: 'Cuarto Año — Educación Física — Inst.' },
    { value: 'rawData.NOTA.CA.5', label: 'Quinto Año — Castellano — Nota' },
    { value: 'rawData.LITERAL.CA.5', label: 'Quinto Año — Castellano — Literal' },
    { value: 'rawData.EVAL.CA.5', label: 'Quinto Año — Castellano — Evaluación' },
    { value: 'rawData.MES.CA.5', label: 'Quinto Año — Castellano — Mes' },
    { value: 'rawData.AÑO.CA.5', label: 'Quinto Año — Castellano — Año' },
    { value: 'rawData.INST.CA.5', label: 'Quinto Año — Castellano — Inst.' },
    { value: 'rawData.NOTA.IN.5', label: 'Quinto Año — Inglés — Nota' },
    { value: 'rawData.LITERAL.IN.5', label: 'Quinto Año — Inglés — Literal' },
    { value: 'rawData.EVAL.IN.5', label: 'Quinto Año — Inglés — Evaluación' },
    { value: 'rawData.MES.IN.5', label: 'Quinto Año — Inglés — Mes' },
    { value: 'rawData.AÑO.IN.5', label: 'Quinto Año — Inglés — Año' },
    { value: 'rawData.INST.IN.5', label: 'Quinto Año — Inglés — Inst.' },
    { value: 'rawData.NOTA.MA.5', label: 'Quinto Año — Matemáticas — Nota' },
    { value: 'rawData.LITERAL.MA.5', label: 'Quinto Año — Matemáticas — Literal' },
    { value: 'rawData.EVAL.MA.5', label: 'Quinto Año — Matemáticas — Evaluación' },
    { value: 'rawData.MES.MA.5', label: 'Quinto Año — Matemáticas — Mes' },
    { value: 'rawData.AÑO.MA.5', label: 'Quinto Año — Matemáticas — Año' },
    { value: 'rawData.INST.MA.5', label: 'Quinto Año — Matemáticas — Inst.' },
    { value: 'rawData.NOTA.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Nota' },
    { value: 'rawData.LITERAL.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Literal' },
    { value: 'rawData.EVAL.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Evaluación' },
    { value: 'rawData.MES.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Mes' },
    { value: 'rawData.AÑO.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Año' },
    { value: 'rawData.INST.EN.5', label: 'Quinto Año — Estudios de la Naturaleza — Inst.' },
    { value: 'rawData.NOTA.HV.5', label: 'Quinto Año — Historia de Venezuela — Nota' },
    { value: 'rawData.LITERAL.HV.5', label: 'Quinto Año — Historia de Venezuela — Literal' },
    { value: 'rawData.EVAL.HV.5', label: 'Quinto Año — Historia de Venezuela — Evaluación' },
    { value: 'rawData.MES.HV.5', label: 'Quinto Año — Historia de Venezuela — Mes' },
    { value: 'rawData.AÑO.HV.5', label: 'Quinto Año — Historia de Venezuela — Año' },
    { value: 'rawData.INST.HV.5', label: 'Quinto Año — Historia de Venezuela — Inst.' },
    { value: 'rawData.NOTA.EF.5', label: 'Quinto Año — Educación Física — Nota' },
    { value: 'rawData.LITERAL.EF.5', label: 'Quinto Año — Educación Física — Literal' },
    { value: 'rawData.EVAL.EF.5', label: 'Quinto Año — Educación Física — Evaluación' },
    { value: 'rawData.MES.EF.5', label: 'Quinto Año — Educación Física — Mes' },
    { value: 'rawData.AÑO.EF.5', label: 'Quinto Año — Educación Física — Año' },
    { value: 'rawData.INST.EF.5', label: 'Quinto Año — Educación Física — Inst.' },
  ]},
,
  { group: 'Plantel por Materia (Constancia)', bindings: [
    { value: 'rawData.INST_NAME.CA.1', label: 'Nombre Plantel - Castellano (1)' },
    { value: 'rawData.INST_LOCAL.CA.1', label: 'Localidad Plantel - Castellano (1)' },
    { value: 'rawData.INST_EF.CA.1', label: 'E.F. Plantel - Castellano (1)' },
    { value: 'rawData.INST_NAME.CA.2', label: 'Nombre Plantel - Castellano (2)' },
    { value: 'rawData.INST_LOCAL.CA.2', label: 'Localidad Plantel - Castellano (2)' },
    { value: 'rawData.INST_EF.CA.2', label: 'E.F. Plantel - Castellano (2)' },
    { value: 'rawData.INST_NAME.CA.3', label: 'Nombre Plantel - Castellano (3)' },
    { value: 'rawData.INST_LOCAL.CA.3', label: 'Localidad Plantel - Castellano (3)' },
    { value: 'rawData.INST_EF.CA.3', label: 'E.F. Plantel - Castellano (3)' },
    { value: 'rawData.INST_NAME.CA.4', label: 'Nombre Plantel - Castellano (4)' },
    { value: 'rawData.INST_LOCAL.CA.4', label: 'Localidad Plantel - Castellano (4)' },
    { value: 'rawData.INST_EF.CA.4', label: 'E.F. Plantel - Castellano (4)' },
    { value: 'rawData.INST_NAME.CA.5', label: 'Nombre Plantel - Castellano (5)' },
    { value: 'rawData.INST_LOCAL.CA.5', label: 'Localidad Plantel - Castellano (5)' },
    { value: 'rawData.INST_EF.CA.5', label: 'E.F. Plantel - Castellano (5)' },
  ]}
]
